### ISSUE TITLE
Fix ooni backend addresses used by regress tests

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/measurement-kit#101]
In an email exchange @hellais suggested:

- to use 213.138.109.232 as backend for http_invalid_request_line

- to use one or more of the [URLs published by Citizen Lab](https://github.com/citizenlab/test-lists/blob/master/csv/global.csv) for tcp_connect

- to use 197.156.64.3 as backend for dns_injection

**Comment by AntonioLangiu** [comment]
The URL you post above is no more reachable. I think they change the directory where it was contained and now the updated URL should be [this](https://github.com/citizenlab/test-lists/blob/master/lists/global.csv). @bassosimone Can you confirm it?

**Comment by bassosimone** [comment]
@AntonioLangiu yes! Having briefly looked at the list, I propose to use archive.org, whaddya reckon?

**Comment by AntonioLangiu** [comment]
I'm using this ip "8.8.8.1" for the dns_injection, like in [the dns_injection test of ooni](https://github.com/TheTorProject/ooni-probe/blob/master/ooni/nettests/experimental/dns_injection.py#L10).

**Comment by bassosimone** [comment]
Part of this has been fixed by #254 and the remainder will be addressed by #253.
