### ISSUE TITLE
Fix redundant code in dns/system resolver

### ISSUE THREAD

**Issue by AntonioLangiu** [measurement-kit/measurement-kit#1025]
In this [part of code](https://github.com/measurement-kit/measurement-kit/blob/master/src/libmeasurement_kit/dns/system_resolver_impl.hpp#L119) of the system resolver there are too much checks.

**Comment by bassosimone** [comment]
I have refactored the code in #1234. After reading it carefully, I didn't see redundancy. Anyway, some redundancy may also lead to robustness, which is good. Closing the issue.
