### ISSUE TITLE
Testing of v0.4.0 with Android devices

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/measurement-kit#1051]
We will test [example-android](https://github.com/measurement-kit/example-adroid) and/or [ooniprobe-android](https://github.com/measurement-kit/ooniprobe-android) using several emulators and devices. The objective is to make a grid of APIs level and architectures where measurement-kit v0.4.0 is known to work:

# Works

- [x] emulator: example-android, nexus 5, API 24, arm64-v8a
- [x] emulator: example-android, nexus S, API 19, armeabi-v7a
- [x] emulator: example-android, nexus 5, API 17, mips
- [x] emulator: example-android, nexus S, API 16, armeabi-v7a
- [x] emulator: example-android, nexus S, API 16, mips
- [x] emulator: ooniprobe-android, nexus 4, API 10, x86
- [x] emulator: ooniprobe-android, nexus 4, API 16, x86
- [x] emulator: ooniprobe-android, nexus 5, API 25, x86

# Does not work
- [x] emulator: example-android, nexus S, API 13, armeabi: segfaults
- [x] emulator: example-android, nexus S, API 10, armeabi-v7a: does not validate certificates
- [x] emulator: example-android, nexus S, API 9, armeabi: segfaults

Cc: @lorenzoPrimi

**Comment by lorenzoPrimi** [comment]
I thionk we should test API 10, armeabi and we can remove the support of APO9

**Comment by bassosimone** [comment]
# armeabi

So, I've cross-compiled the `measurement_kit` binary for `armeabi`, instrumented the code to print more log messages, pushed the binary to a device and executed it from inside the device. It seems that the code crashes somewhere inside of libevent when it tries to create an `event_base`:

```
$ adb push jniLibs/armeabi/measurement_kit_exe /data/local/tmp
[100%] /data/local/tmp/measurement_kit_exe
$ adb shell
root@android:/ # ./data/local/tmp/measurement_kit_exe tcp_connect -vvv www.google.com
before the assert
before making reactor
[!] we are at the end of the library singleton!
[!] we are about to try to alloc evbase
[warn] event_base_new_with_config: no event mechanism available
[1] + Stopped (signal)     ./data/local/tmp/measurement_kit_exe
root@android:/ # 
[1] + Segmentation fault   ./data/local/tmp/measurement_kit_exe
root@android:/ #
```

Now, it would probably make sense to try to understand why this is happening.

**Comment by bassosimone** [comment]
After the changes described above, the situation is the following:

# Works
- [ ]  emulator: example-android, nexus S, API 16, armeabi-v7a: works

# Does not work
- [ ] emulator: example-android, nexus S, API 13, armeabi: segfaults
- [ ] emulator: example-android, nexus S, API 10, armeabi-v7a: does not validate certificates

Compared to the previous situation, now the segmentation fault does not happen immediately but rather when the SSL connection is being established. The situation is unchanged with `armeabi-v7a` where certificate verification fails. I wonder whether the two problems are somehow connected.

**Comment by bassosimone** [comment]
# armeabi

Investigating further, I noticed that android-ndk/ndk#144 to avoid using the integrated assembler for compiling OpenSSL on Android. Honestly, when reading this issue it was not clear to me how this could apply to the case at hand (armeabi) because assembly generation is already disabled. However, it turns out that passing that flag when building dependencies fixed armeabi. I guess in some way the assembler integrated into clang is not working well in all cases on armeabi. This is also something that can be possibly investigated further to understand the real root cause.

The simple diff adding `-fno-integrated-as` has been implemented in 19d0c73.

**Comment by bassosimone** [comment]
This is now done. I'll finish off it tomorrow morning, when I'll merge #1047

**Comment by bassosimone** [comment]
We can close this issue now.
