### ISSUE TITLE
android: ssl cert verification not working with armeabi-v7a API 10 emulator

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/measurement-kit#1054]
During #1051, we tested measurement-kit on a variety of emulated devices and on some real devices using different architectures (basically all except mips64) and APIs. The only case where the library was not working is with armeabi-v7a and API 10, where SSL certificate verification consistently failed:

> /ooni: query mlabns for tool ndt
> D/ooni: mlabns url: https://mlab-ns.appspot.com/ndt
> D/ooni: http::request: {
> D/ooni: http::request:     dns/engine => system
> D/ooni: http::request:     geoip_asn_path => /data/data/org.openobservatory.measurement_kit_android_sample/files/geoipasnum.dat
> D/ooni: http::request:     geoip_country_path => /data/data/org.openobservatory.measurement_kit_android_sample/files/geoip.dat
> D/ooni: http::request:     http/method => GET
> D/ooni: http::request:     http/url => https://mlab-ns.appspot.com/ndt
> D/ooni: http::request:     no_file_report => 1
> D/ooni: http::request:     save_real_probe_ip => 1
> D/ooni: http::request:     test_suite => 4
> D/ooni: http::request: }
> D/ooni: resolve_hostname: mlab-ns.appspot.com
> D/ooni: resolve_hostname: ipv4...
> [...]
> D/ooni: resolve_hostname: ipv4... done
> D/ooni: resolve_hostname: ipv6...
> D/ooni: resolve_hostname: ipv6... done
> D/ooni: connect_first_of begin
> D/ooni: connect_base 172.217.23.113:443
> D/ooni: connect time: 0.037545
> D/ooni: connect_first_of success
> D/ooni: ca_bundle_path: 
> D/ooni: connect ssl...
> D/ooni: connect ssl... callback
> D/ooni: error in connection.
> W/ooni: Test failed: {unknown_failure 8024} [{ssl_error error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed}]

Interestingly, this does not happen in many other armeabi-v7a emulators. Plus, I have an armeabi-v7a device (a nexus 7 with API 23) where the android-example app works fine as well.

For this reason, and also given that armeabi-v7a only became widely used after API 16 [*], with @lorenzoPrimi we decided to close #1051 and fill this bug report for future investigation.

I suspect that tweaking the flags with which libressl is compiled (perhaps passing `-fno-builtin-as` to the compiler) may solve the issue. Also a newer NDK may solve the issue (or introduce new issues).

- - -
[*] This is my guess based on the fact that there is only one armeabi-v7a emulator available for download in Android Studio before API 16 and there are no available armeabi emulators after API 16.

**Comment by bassosimone** [comment]
With v0.4.1, same conditions, I see this:

```
connect ssl... callback
error in connection.
Opening report... 3
[...]
connect ssl... callback
error in connection.
Test failed: {ndt_error_querying_mlabns} [{value_error}]
```

Now, this is interesting because the error *seems* different than before. And, for the records, 3 is the equivalent of `value_error`.

**Comment by bassosimone** [comment]
Not relevant anymore: now the NDK only supports from API 14 onwards.

**Comment by lorenzoPrimi** [comment]
The Android APK now supports API 15 minimum

**Comment by bassosimone** [comment]
No, [the minimum in the NDK is 14](https://android.googlesource.com/platform/ndk/+/ndk-r15-release/CHANGELOG.md):

> Gingerbread (android-9) is no longer supported. The minimum API level target in the NDK is now Ice Cream Sandwich (android-14). If your APP_PLATFORM is set lower than android-14, android-14 will be used instead.

**Comment by lorenzoPrimi** [comment]
I was talking about the ooniprobe-android app, sorry :D

**Comment by bassosimone** [comment]
Ah, LOL. Great, then we basically have the libraries and the App mostly aligned :-)
