### ISSUE TITLE
When specifying a maximum runtime the progress should be accurate

### ISSUE THREAD

**Issue by hellais** [measurement-kit/measurement-kit#1058]
Currently the progress for measurement-kit is dependent on how many entries are inside of the input file and is a percentage of how many are completed/total.

When a maximum runtime is specified the progress should be in relation to the maximum runtime of the test.

Moreover it would be even better if the progress were not just related to running the measurements, but also takes into account bootstrap (looking up of the IP of the probe) and shutdown on the test (closing the report).

**Comment by bassosimone** [comment]
Addressed in c3ddfbf.
