### ISSUE TITLE
Add ability to run MK tests from ooniprobe

### ISSUE THREAD

**Issue by joelanders** [measurement-kit/measurement-kit#1086]
After the control-port is done in MK, make ooniprobe talk to it.

**Comment by hellais** [comment]
xref: https://github.com/TheTorProject/ooni-probe/issues/558

**Comment by bassosimone** [comment]
We're currently exploring another approach which is creating bindings for other languages. We have done a prototype for Python and we're now trying to write a prototype for Node.js.

**Comment by bassosimone** [comment]
I am going to close this, since now we have nodejs bindings unless @hellais objects quickly!

**Comment by bassosimone** [comment]
@hellais suggested to keep this open for a little more.

**Comment by bassosimone** [comment]
We have clearly sorted out how to do this.
