### ISSUE TITLE
IM server reachability test

### ISSUE THREAD

**Issue by joelanders** [measurement-kit/measurement-kit#1087]
https://github.com/TheTorProject/ooni-spec/blob/master/test-specs/ts-018-whatsapp.md
https://github.com/TheTorProject/ooni-spec/blob/master/test-specs/ts-019-facebook-messenger.md

It sounds like the implementations of these will have a lot in common, so try to template it so that we can test new IM apps without much code duplication.

**Comment by bassosimone** [comment]
See #1191, #1192, #1193.

**Comment by bassosimone** [comment]
I guess we can close this issue: we have open PRs for each test.
