### ISSUE TITLE
Improve how scrubbing and encoding is handled

### ISSUE THREAD

**Issue by hellais** [measurement-kit/measurement-kit#1110]
In #1106 we concluded that we should be managing better how encoding and scrubbing happens.

Namely the correct place to do scrubbing (and also encoding) is at the level of the `nettest:Runnable` by means of defining the fields that should be scrubbed and encoded inside of the metadata of the test and test template.

It would be nice to defined something like:

```
"to_encode": {"test_keys": {"response": ["response_line", "body", "headers"]},
"to_scrub": {"test_keys": {"response": ["body", "headers"]}}
```

inside of the specification of the test and based on this metadata perform the scrubbing in `nettest:Runnable`

**Comment by bassosimone** [comment]
We're not working on this. (Also, an auto-closing-bot-like feature may be nice because old issues disappear and I don't understand the value in keeping them open and hidden. Maybe this is telling us that we need some procedures to sometimes go over the backlog?)
