### ISSUE TITLE
OONI mobile: NDT saves user IP address on server side

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/measurement-kit#1112]
[edit: I've significantly simplified the description of this issue.]

# Problem

OONI mobile by default does not save user's IP address and sends `127.0.0.1` to its collector backend instead (unless the user overrides the default setting).

NDT servers instead always save the user's IP address.

What would be *surprising* for users is that their IP address would be saved *despite* they have configured OONI mobile not to do so.

Furthermore, an attacker may somehow use NDT data to enumerate OONI mobile users. (This can also be done by capturing packets, etc., with a significantly higher effort, tho.)

# Solution

We *should* probably tell explicitly to OONI mobile users that their IP address is going to end up into NDT servers logs, published openly. (This would probably discourage NDT tests.)

We *may* want to extend the NDT protocol to cope with this use case, and we *may* consider implementing that initially only on botticelli and propose a diff for NDT.

- - -

Strictly speaking, this *may not* even be an issue of measurement-kit per se, but I am opening the issue here and think that we can eventually create specific issues for each app, and I think that in any case some action items to handle / mitigate this issue may be implemented here anyway.

Thoughts?

/cc: @agrabeli

**Comment by agrabeli** [comment]
@bassosimone I agree that we have a responsibility of inform OONI mobile app users that their IP addresses will be collected by NDT servers (though it would be great if users could opt-out from this). 

As part of next steps to inform users, I'll edit the following documentation to notify users that their IP addresses will be collected by NDT servers when/if they run OONI's NDT test:

1. NDT test description (https://ooni.torproject.org/nettest/ndt/)

2. OONI's Data Policy (https://ooni.torproject.org/about/data-policy/)

3. OONI's Risks documentation (https://ooni.torproject.org/about/risks/)

It would also be useful to include a disclaimer about this directly in the NDT test description included in OONI's mobile app.

**Comment by bassosimone** [comment]
I think we can now close this issue, given that we've edited all what was mentioned above!
