### ISSUE TITLE
Android app "local reference table overflow" crash

### ISSUE THREAD

**Issue by lorenzoPrimi** [measurement-kit/measurement-kit#1125]
This crash happened a few times when running ooniprobe-android 1.1.1 on a x86 simulator.

[log.txt](https://github.com/measurement-kit/measurement-kit/files/763522/log.txt)

**Comment by bassosimone** [comment]
I think @hellais has find the reason why this is crashing, and it is basically that in JNI code we do not properly cleanup temporarily allocated objects in callbacks. We'll do more testing and merge the fix in the measurement-kit/android-libs repository.

**Comment by bassosimone** [comment]
Migrated as: https://github.com/TheTorProject/ooniprobe-android/issues/60
