### ISSUE TITLE
connect() failed in its callback.

### ISSUE THREAD

**Issue by lorenzoPrimi** [measurement-kit/measurement-kit#1126]
Happens when running ooniprobe-android 1.1.1 without `.set_options("parallelism", "1")`
There are no explications on why and where it happens, and moreover why happens a lot without parallelism.
The error is 
`
W/ooni: connect() failed in its callback`
`
W/ooni: reason why connect() has failed: connection_refused
`

Sometimes i get `generic_timeout_error` but I guess that is a true timeout of the website

**Comment by bassosimone** [comment]
I have added more context to the error in #1136
