### ISSUE TITLE
Create PPA for Ubuntu

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/measurement-kit#1148]

**Comment by bassosimone** [comment]
@irl is it possible to create the PPA using the code you're working as part of #1194?

**Comment by irl** [comment]
Don't make a PPA, you can just add the deb.tpo repository. I'm looking at some of this now.

**Comment by bassosimone** [comment]
> Don't make a PPA, you can just add the deb.tpo repository.

Ah, okay, great! Then, I guess I can close this issue as superseded by #1194. Thanks!
