### ISSUE TITLE
dns: where possible, gather CNAME

### ISSUE THREAD

**Issue by hellais** [measurement-kit/measurement-kit#1270]
@darkk noticed in https://github.com/TheTorProject/ooni-pipeline/pull/62 that:

>  control_failure [ambiguous] is stamped at ~27% of dns_a rows, that's likely a bug

It seems this is only affecting measurements from the mobile apps, so it's likely a bug in measurement-kit.

We should look into this fact and figure out what is going on.

**Comment by darkk** [comment]
That's not MK bug, it's centrifugation step bug. `[ambiguous]` is stamped on inability to deduce hostname used for control query as control server does not give us hostname that was used to produce the control measurement output.

There is another bug that is relevant for MK: CNAME chain from DNS reply is not recorded for MK-based measurements. I'm unsure if it's known and if it's already fixed. I assume that it's known and not fixed as MK was using libevent DNS code for queries some time ago and libevent hides CNAMEs from user.

**Comment by bassosimone** [comment]
> I assume that it's known and not fixed as MK was using libevent DNS code for queries some time ago and libevent hides CNAMEs from user.

Correct. Renaming the issue as such.

**Comment by bassosimone** [comment]
This will be deferred to v0.8 (or to a patch release of v0.7)
