### ISSUE TITLE
web_connectivity: slow regex to extract title (when body is huge)

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/measurement-kit#1277]
As mentioned in #1276:

> The specific, aggressive regular expression is the one for extracting the title.
>
> In addition [...], evaluating the regexp over long bodies is also very expensive. I have seen MK freezing for seconds when searching for the title (again: on my Mac mini). [...]

Perhaps we can mitigate this issue by trying to evaluate the regexp on an initial slice of the body.

(I think that slicing the body is a good fix for the slowness, but not to prevent the segfault documented in #1276, which instead should be addressed by using a C++ library that works better, see #1275)

**Comment by bassosimone** [comment]
This should be addressed in v0.8.0!

**Comment by darkk** [comment]
> aggressive regular expression

My usual hack against that agression is `<title>([^<]*)</title>`. Maybe that'll eventually be useful.

**Comment by bassosimone** [comment]
@darkk Thanks! I've tried your fix in #1494 and it seems to work.

**Comment by bassosimone** [comment]
Since there is no consensus on how to move forward on this, I'm shifting it to `v0.9.0`.

**Comment by bassosimone** [comment]
Mitigation deployed in `v0.9.0-beta`. Re-instated @darkk's suggestion with more luck using `<title>([^<]{1,128})<\/title>`. If we see issues again, we can use `re2`.
