### ISSUE TITLE
Please provide pkg-config data

### ISSUE THREAD

**Issue by irl** [measurement-kit/measurement-kit#1339]
This is handy mostly for people installing from source as it makes it easier to deal with non-standard installation locations. Also it's handy for autoconf style configure scripts to detect the presence of measurement-kit.

https://people.freedesktop.org/~dbn/pkg-config-guide.html#writing

**Comment by bassosimone** [comment]
Yes, I think that would be useful !

**Comment by bassosimone** [comment]
We're not going to add MK to Debian, so it doesn't matter for now.
