### ISSUE TITLE
Log not written for dash test

### ISSUE THREAD

**Issue by lorenzoPrimi** [measurement-kit/measurement-kit#1391]
As @bassosimone spotted, when the verbosity is set to MK_LOG_INFO, no log is written for the dash test.
Did a test with verbosity MK_LOG_DEBUG2 and the log was written.
mk v0.7.4

**Comment by bassosimone** [comment]
Thanks!

**Comment by bassosimone** [comment]
I fixed this in `v0.7.5` and #1394
