### ISSUE TITLE
Add support for testing censorship circumvention tools

### ISSUE THREAD

**Issue by hellais** [measurement-kit/measurement-kit#1399]
Currently MK doesn't support testing reachability of any censorship circumvention tools.

This epic is used to collect all the tickets related to adding support for the various censorship circumvention tools out there.

**Comment by bassosimone** [comment]
@hellais wrote:

> Psiphon: https://github.com/TheTorProject/ooni-probe/issues/744, #1425

✅  Implemented in ooni/probe-engine.

> Tor pluggable transports: #1426

🗒 in https://github.com/ooni/probe-engine/issues/79

> OpenVPN: #1418

🗒 in https://github.com/ooni/probe-engine/issues/45

> Lantern: #1400

🗒 in https://github.com/ooni/probe-engine/issues/80

> Tor integration: #86

🗒 in https://github.com/ooni/probe-engine/issues/81
