### ISSUE TITLE
Add support for testing lantern

### ISSUE THREAD

**Issue by hellais** [measurement-kit/measurement-kit#1400]
It would be nice to also support testing lantern as part of measurement-kit.

@oxtoacart do you have suggestion on how we could link lantern inside of a C++ library and what golang functions we should be calling to:

* Start lantern and check that it bootstrapped properly
* Stop lantern cleanly so that we can then repeat an experiment

Is there anything else we should be aware of that would aid the integration?

**Comment by oxtoacart** [comment]
@hellais Lantern can be run from the command-line. Would it be sufficient to execute the commend from measurement-kit and check the logs for successful startup?

**Comment by hellais** [comment]
@oxtoacart thanks for getting back to us on this!

Since measurement-kit is targeting mobile platforms, we have limitations on some of these platform (for example iOS) in terms of what we can do with processes (on iOS you can't start a process).

What would be ideal for us to make integration easier, is find a way to link to lantern directly and call some function that does the equivalent of what is called by the CLI when the command is run.

**Comment by oxtoacart** [comment]
Got it. I've opened a ticket on the Lantern side to address this.

**Comment by hellais** [comment]
@oxtoacart outstanding! Thanks so much!

**Comment by joelanders** [comment]
I've actually got an item in my contract to work on this, but I think the dollar-amount might have been assuming we do something simple like shelling out to an executable rather than figuring out how to embed a go program in a c++ library on iOS :)

**Comment by bassosimone** [comment]
Moved here https://github.com/ooni/probe-engine/issues/80
