### ISSUE TITLE
Improve progress handlers for running tests

### ISSUE THREAD

**Issue by hellais** [measurement-kit/measurement-kit#1401]
To provide a better user experience it would be nice to have extra information on progress.

Specifically what I would like to know for web_connectivity is:

* What is the number of test over the total number of tests (as opposed to just xx%)

* What is the URL that is currently being measured when a new one is measured (and maybe when one is completed)

**Comment by bassosimone** [comment]
Alright. I think we can have this landing in v0.9.0.

**Comment by bassosimone** [comment]
@hellais I would suggest to check whether you current proposal regarding events to be emitted incorporates this feedback and, if so, close or just update this ticket.

**Comment by hellais** [comment]
A good call. I did include some part of this (reporting back on the currently being tested url), but didn't include the URL idx over total. We should remember to add that to it.

I would in any case keep these tickets open until the features are implemented otherwise we may forget.

**Comment by bassosimone** [comment]
This is not preventing us from making a release. Deferring to `v0.10.0`.

**Comment by bassosimone** [comment]
It doesn't make sense to implement this functionality in v0.9.1, because we now have OONI v2.0 that is not using this functionality, therefore we will postpone it to v0.10.0.

**Comment by bassosimone** [comment]
Postponing with v0.11.0 with the same rationale as above. In a more general fashion, I'd like to avoid changing the test workflow until the cURL based code has been merged to replace all the communications with backends etc, which is due in v0.10.0. This should help me to reduce the amount of code that I should change twice in a short time frame.

**Comment by bassosimone** [comment]
This has now become irrelevant for the following reason:

1. the mobile app does not care about it

2. OONI for Desktop does not need this functionality because the way in which we run tests in github.com/ooni/probe-engine is such that these events are not used.
