### ISSUE TITLE
Collect infra-request timing

### ISSUE THREAD

**Issue by hellais** [measurement-kit/measurement-kit#1414]
It would be cool to also collect infra request (for example, DNS query to DNS response, TCP Connect, etc.) timing information.

This can be useful to detect instances of throttling.

**Comment by bassosimone** [comment]
@hellais those information are already collected by MK but not used by the OONI helpers. I think, if you can sketch out how these information needs to end up into the JSON files, we can quite easily get rid of this issue in a very short time frame. (There are some potential issues in regards to collecting DNS timing with the system-wide resolver, tho, because my understanding is that the response can be cached locally and, as such, it can be insanely fast; also, the system-wide collector would hide events such as DNS timeouts and the like.)

**Comment by hellais** [comment]
Right, so this is more about extending the data format spec to support this sort of use-case. For this purpose I filed: https://github.com/TheTorProject/ooni-spec/issues/91.

I think we should leave this open though until that happens.

**Comment by bassosimone** [comment]
Great!

**Comment by bassosimone** [comment]
@hellais reminder that I can provide more data when the spec is updated!

**Comment by hellais** [comment]
Some extra thoughts on this topic (it's probably also useful to check out the browser telemetry project: https://firefox-source-docs.mozilla.org/toolkit/components/telemetry/telemetry/).

Timing information that I think should be gathered (and that should be gathered on a per HTTP(s) request basis):

* DNS resolution time (delta between request being issued to receiving of the first response, possibly a vector to capture the timing in the case of multiple responses)
* TCP Connect delta
* TLS handshake delta
* Time to first byte (maybe it's good to distinguish the time for first byte in the case of TLS vs non-TLS traffic)
* Delta between time to first byte vs receiving all the response

Maybe this is unrelated to this feature, but it's worthwhile thinking about it within this scope, to record the reason for the shutdown (did the connected get RST by the server, was it closed by the client, etc.).

@bassosimone do you think I am missing something?

**Comment by hellais** [comment]
Another useful source of inspiration for timing information collection is the HAR spec: https://w3c.github.io/web-performance/specs/HAR/Overview.html#sec-object-types-timings.

Copy pasting the text in here:

timings

This object describes various phases within request-response round trip. All times are specified in milliseconds.

"timings": {
    "blocked": 0,
    "dns": -1,
    "connect": 15,
    "send": 20,
    "wait": 38,
    "receive": 12,
    "ssl": -1,
    "comment": ""
}
blocked [number, optional] - Time spent in a queue waiting for a network connection. Use -1 if the timing does not apply to the current request.
dns [number, optional] - DNS resolution time. The time required to resolve a host name. Use -1 if the timing does not apply to the current request.
connect [number, optional] - Time required to create TCP connection. Use -1 if the timing does not apply to the current request.
send [number] - Time required to send HTTP request to the server.
wait [number] - Waiting for a response from the server.
receive [number] - Time required to read entire response from the server (or cache).
ssl [number, optional] (new in 1.2) - Time required for SSL/TLS negotiation. If this field is defined then the time is also included in the connect field (to ensure backward compatibility with HAR 1.1). Use -1 if the timing does not apply to the current request.
comment [string, optional] (new in 1.2) - A comment provided by the user or the application.
The send, wait and receive timings are not optional and must have non-negative values.

An exporting tool can omit the blocked, dns, connect and ssl, timings on every request if it is unable to provide them. Tools that can provide these timings can set their values to -1 if they don’t apply. For example, connect would be -1 for requests which re-use an existing connection.

The time value for the request must be equal to the sum of the timings supplied in this section (excluding any -1 values).

Following must be true in case there are no -1 values (entry is an object in log.entries) :

entry.time == entry.timings.blocked + entry.timings.dns +
    entry.timings.connect + entry.timings.send + entry.timings.wait +
    entry.timings.receive;

**Comment by bassosimone** [comment]
Consolidated into https://github.com/ooni/probe-engine/issues/12
