### ISSUE TITLE
IPv6 Testing

### ISSUE THREAD

**Issue by willscott** [measurement-kit/measurement-kit#1415]
Currently, MK tests are still have some IPv4 assumptions. It would be great to extend the testing to include a comparison with v6 connectivity to determine how access to sites differ when using a v6 connection.

This involves:

* [ ] AAAA dns lookups.
* [ ] Explicit connection attempts to v6 hosts.
* [ ] HTTP requests over both v4 and v6 connections

**Comment by bassosimone** [comment]
I agree! Do you think this could be something done as part of web connectivity or something that is to be performed as a separate test?

**Comment by hellais** [comment]
I think this should be done a separate test and should probably fit well inside of the tests of the "Performance" group (it's not strictly performance, but it's in a way related to network characteristics that are not related to censorship).

Digging into the cisco DNS data, I think some good target domains to resolve could be:

* ipv6.msftncsi.com (ranked 566)
* 6to4.ipv6.microsoft.com (ranked 4300)
* ipv6.login.live.com (ranked 8569)

A good test case is trying to reach:

http://ipv6.msftconnecttest.com/connecttest.txt

Which fails on non ipv6 networks (this domain is ranked 4733)

Moreover we could possibly also use `ipv6.whatismyip.akamai.com` to get the ipv6 address of the client.

This also supports domain fronting with the akamai ipv6 endpoint:

```
curl -H "Host: ipv6.whatismyip.akamai.com" a978.i6g1.akamai.net
```

In grepping through the cisco domains I noticed that useful patterns to search for to spot ipv6 hostnames are:

* `ipv6`
* `i6`
* `v6`

**Comment by bassosimone** [comment]
Is now https://github.com/ooni/probe-engine/issues/812
