### ISSUE TITLE
Add additional fingerprinting in http_invalid_request_line test 

### ISSUE THREAD

**Issue by willscott** [measurement-kit/measurement-kit#1416]
Currently, https://github.com/measurement-kit/measurement-kit/blob/master/src/libmeasurement_kit/ooni/http_invalid_request_line.cpp tests 4 patterns:

* randomSTR(4) + " / HTTP/1.1\n\r"
* ' '.join(randomStr(5) for x in range(4)) + '\n\r'
* randomStr(1024) + ' / HTTP/1.1\n\r'
* 'GET / HTTP/' + randomStr(3)

In addition, we should consider detection of pseudo-schemes for some specific middle boxes:

* 'GET cache_object://localhost/ HTTP/1.0\r\n' can trigger specific behavior in Squid
* 'GET http://localhost:8123/polipo/ HTTP/1.0\r\n' may trigger specific behavior in Polipo proxies

There may be similar ones for e.g. mikrotik and other common proxies.

**Comment by hellais** [comment]
Also HTTP Header Field Manipulation is related to this.

**Comment by bassosimone** [comment]
> Also HTTP Header Field Manipulation is related to this.

Right. I am wondering: cannot we somehow have a single test for all of this?

**Comment by bassosimone** [comment]
@willscott can we consider this issue closed, or should we also strive to implement the polipo case?

**Comment by willscott** [comment]
It would be great to come up with finger prints for a few more commonly available / known proxies.  I think Polipo and Mikrotic at least if possible. I think this lowers priority back down to a wish-list / when someone gets around it it, but there's certainly still work to be done here.

**Comment by bassosimone** [comment]
I don't like issues being open forever. I guess we should close this and add new signatures when we encounter new middle-boxes as separate issues. There were no GitHub projects when we created this issue, but I'd argue that this could have been a project rather than an issue.
