### ISSUE TITLE
Follow-up measurement: gather more DNS records

### ISSUE THREAD

**Issue by anadahz** [measurement-kit/measurement-kit#1417]
Add support to get the (MX) mail exchanger record(s) of a given input in the web connectivity test.

**Comment by bassosimone** [comment]
@anadahz @hellais do you think we should do this as part of web connectivity or is this something to be added as part of another test, or both?

FTR, this depends on us having support for c-ares.

**Comment by hellais** [comment]
To properly answer I would like to get a feel as to how much extra bandwidth this would cost and some use-cases of where this would be relevant.

That said I think Web Connectivity is already large enough as it is and probably we want this to be part of some other tests that is maybe triggered based on WC test results.

**Comment by bassosimone** [comment]
> That said I think Web Connectivity is already large enough as it is and probably we want this to be part of some other tests that is maybe triggered based on WC test results.

I like this ideally. Ideally we can make web-connectivity a little less fat and reorder the operations such that stuff that is not necessarily needed is only executed as a follow up.

**Comment by willscott** [comment]
Suggestion: rename to not just MX record, but 'more DNS' records.

Ideally we would make separate DNS requests for

* MX
* TXT
* AAAA
* With dnssec requested

**Comment by bassosimone** [comment]
Moved here https://github.com/ooni/probe-engine/issues/84
