### ISSUE TITLE
Add OpenVPN test

### ISSUE THREAD

**Issue by anadahz** [measurement-kit/measurement-kit#1418]
Add a test with the ability to measure whether OpenVPN is working from the given network vantage point.

**Comment by hellais** [comment]
related tickets in ooni-probe:
* https://github.com/TheTorProject/ooni-probe/issues/579
* https://github.com/TheTorProject/ooni-probe/issues/519

**Comment by bassosimone** [comment]
How do we implement this?

1. If we want to spawn `OpenVPN` as an external process, the way to go is probably to have a portable way of executing an external executable.

2. If we want to integrate `openvpn` into MK, we have a problem similar to the problem of integrating Tor into MK.

    2.1. We may get away with running the `main` of OpenVPN into a separate thread.

    2.2. Otherwise, another option is to modify `OpenVPN` such that it uses the MK event loop.

All these options are not so simple, except perhaps the first.

**Comment by willscott** [comment]
This may be part of also considering other VPN protocols, like:

* https://www.wireguard.com/
* pptp
* ipsec
* socks5
* shadowsocks

**Comment by hellais** [comment]
The tunnelbear people would be interested in testing the reachability of their VPN endpoints with OONI Probe. We should maybe open a sub-ticket specific to tunnelbear reachability testing and use that as a test case.

cc @jiangyi

**Comment by bassosimone** [comment]
Migrated https://github.com/ooni/probe-engine/issues/45
