### ISSUE TITLE
Meta: Design & Implement Traceroute test

### ISSUE THREAD

**Issue by willscott** [measurement-kit/measurement-kit#1421]
There are several bugs on parts of this meta issue already:
* https://github.com/measurement-kit/measurement-kit/issues/1366
* https://github.com/measurement-kit/measurement-kit/issues/683
* https://github.com/measurement-kit/measurement-kit/issues/205
* https://github.com/measurement-kit/measurement-kit/issues/195
* https://github.com/measurement-kit/measurement-kit/issues/194

The high level design questions we should be considering are:
* What are the privacy implications of such a test, and what sort of redaction should we perform?
* Where should we be trying to traceroute to?
* What methods should we be using? ICMP? TCP / UDP?

**Comment by bassosimone** [comment]
Very good! I am going to convert this into an "Epic" umbrella ticket.

**Comment by bassosimone** [comment]
We should consider using some existing engine like dublin traceroute and/or libtins.

**Comment by joelanders** [comment]
Copying this comment from here (https://github.com/measurement-kit/measurement-kit/issues/1366#issuecomment-341553813)

I have in my contract something traceroute related under the Libtins section:

preliminary/generic libtins integrations
multi-protocol traceroute (libtins dep)
dns spoofing test (libtins dep)
"Multi-Protocol Traceroute" referring to the ooni-probe test that does the TTL trick on TCP packets of varying ports to see if different protocols get routed differently.

I should be implementing that in the next few months, so lemme know if y'all have any other wishes.

**Comment by willscott** [comment]
I think the main design questions are:
* [ ] How do we sanitize trace route output consistent with user privacy (Country, AS, IP) settings?
* [ ] Should we include a reverse trace route w/ helper as part of the trace route test?

**Comment by bassosimone** [comment]
https://github.com/ooni/probe-engine/issues/46
