### ISSUE TITLE
Add Tor pluggable transport tests

### ISSUE THREAD

**Issue by hellais** [measurement-kit/measurement-kit#1426]
We should be testing tor pluggable transports, such as:

* [ ] obfs4
* [ ] meek
* [ ] obfs3

The questions the answer from the Tor team are:

* Can you create a golang shared library that we can link to from MK?

* Does the PT require some form of configuration file, what configuration should we use in Measurement Kit (and OONI Probe) for testing it's reachability?

* How big is the library?

* How should a minimal set of the PT functionality look like in a test?
  - eg. download list of servers?
  - server select?
  - try to connect?
  - try to access site(s)?
  - what API calls should we do?
  - what about false positives eg. Captchas?
  - fixed control server we/they run that serves 1MB, 100kb, or whatever

* What would the PT like to learn from OONI measurements? (i.e. how can we make the test useful not only to us and our community, but also to your development team to improve your software)

* What metrics would the PT like to have access to from the OONI API? - eg. debug information

* Would you like measurements to be made available to the public or would you prefer them to be privately shared just with you?

**Comment by anadahz** [comment]
Perhaps it may be useful to test if fteproxy pluggable transports are reachable, given the fact that the Tor browser include a number of default fteproxy bridges.

**Comment by hellais** [comment]
> Perhaps it may be useful to test if fteproxy pluggable transports are reachable, given the fact that the Tor browser include a number of default fteproxy bridges.

I think given the fact that fteproxy is written in python it's going to be **really** hard to ship this as part of MK.

**Comment by hellais** [comment]
> given the fact that the Tor browser include a number of default fteproxy bridges

Also the latest Tor browser doesn't include fteproxy support anymore:

<img width="594" alt="screen shot 2017-10-10 at 14 57 57" src="https://user-images.githubusercontent.com/424620/31404937-7c4a0bee-adcb-11e7-9ac1-005349b5624a.png">
<img width="416" alt="screen shot 2017-10-10 at 14 58 13" src="https://user-images.githubusercontent.com/424620/31404938-7c598b00-adcb-11e7-9af1-4c4d7d5ac96e.png">

**Comment by Em4E** [comment]
> Also the latest Tor browser doesn't include fteproxy support anymore:

fte is missing on mac and windows 64-bit, but still present on linux 32/64-bit and windows 32-bit.
https://bugs.torproject.org/18495
https://bugs.torproject.org/24195

https://gitweb.torproject.org/builders/tor-browser-build.git/tree/projects/tor-browser/build?id=9dccb03592f801a3ae14a80e41dc05005b86d267#n134
```
[% IF c("var/windows") -%]
  # We don't have snowflake available on Windows yet
  # We don't have fte available on Windows x86_64 yet
  grep -v 'default_bridge\.snowflake' Bundle-Data/PTConfigs/bridge_prefs.js \
  [% IF c("var/windows-x86_64") %]| grep -v 'default_bridge\.fte' [% END %] \
      >> $TBDIR/$EXTOVERRIDESPATH
[% END -%]
[% IF c("var/osx") -%]
  # FTE is temporarily removed due to bug 18495.
  grep -Ev 'default_bridge\.fte' Bundle-Data/PTConfigs/bridge_prefs.js \
  [% IF ! c("var/snowflake") %]| grep -v 'default_bridge\.snowflake' [% END %] \
      >> $TBDIR/$EXTOVERRIDESPATH
[% END -%]
```

**Comment by bassosimone** [comment]
See https://github.com/ooni/probe-engine/issues/79
