### ISSUE TITLE
Distinguish between privacy settings and failure to lookup geoip information

### ISSUE THREAD

**Issue by hellais** [measurement-kit/measurement-kit#1435]
Currently we don't record in the measurement if the ASN is `AS0` because the user has opted out to submitting network information vs the geoip lookup failed.

I noticed this because I found that a old maxmind DB leads to the ASN not being discovered and as a result that is set as `AS0` in the measurement.

It would be useful to maybe write an annotation with the privacy settings so that we can actually distinguish these cases and if we start noticing many of these cases, then we can push an updated geoip DB.

**Comment by bassosimone** [comment]
I'll try to do this in v0.8.0 and, if I don't make it, it will instead end into v0.9.0.

**Comment by bassosimone** [comment]
> It would be useful to maybe write an annotation with the privacy settings so that we can actually distinguish these cases and if we start noticing many of these cases, then we can push an updated geoip DB.

This is a very good idea. I have implemented it in #1674.
