### ISSUE TITLE
Flush standard output more often

### ISSUE THREAD

**Issue by hellais** [measurement-kit/measurement-kit#1436]
I believe that currently measurement-kit doesn't flush `stdout` as often as it flushes `stderr`. This results in not being able to reliably use `stdout` of the `measurement_kit` CLI to be able to report progress update in realtime to the user.

This probably will also lead to out of order output when the user redirects both stderr and stdout to a file.

An example of this can be seen by running:

```
measurement_kit ndt &> /tmp/sample.out
```

And then looking at the output to confirm that it is in fact out of order:

```
Contacting bouncer: https://bouncer.ooni.io
Using discovered collector: https://c.collector.ooni.io:443
Your public IP address: XXX
Error Opening file GeoIP.dat
[!] cannot open geoip database: GeoIP.dat
[!] cannot lookup country code: {cannot_open_geoip_database}
Error Opening file GeoIPASNum.dat
[!] cannot open geoip database: GeoIPASNum.dat
[!] cannot lookup asn: {cannot_open_geoip_database}
Results collector: https://c.collector.ooni.io:443
Opening report; please be patient...
Report ID: 20171021T114412Z_AS0_R3NB3XmrI8auT7g6g2bStXwFhFB7hF2yVga7iNJxnuPCHqL7nC
Discovered mlab test server: ndt.iupui.mlab1.mil05.measurement-lab.org
Server version: v4.0.0.1-Web100
Connected to ndt.iupui.mlab1.mil05.measurement-lab.org:57749
Starting upload
Elapsed enough time
Ending upload (0)
Connection to ndt.iupui.mlab1.mil05.measurement-lab.org:57749 closed
C2S speed calculated by server: 14798 kbit/s
Submitting test results; please be patient...
Results successfully submitted
Closing report; please be patient...
Report successfully closed
5%: geoip lookup
10%: open report
11%: Connected to test server
12%: Waiting for our turn in queue
13%: Authorized to run test
14%: Got server version
15%: Got authorized tests identifiers
17%: upload-speed (elapsed 0.51 s) 15796.39 kbit/s (num_streams 1)
[... snip ...]

Test summary
------------
Upload speed: 16393.29 kbit/s
Download speed: 16649.07 kbit/s
Packet loss rate: 0.04%
Out of order: 25.42%
RTT (min/avg/max): 16.00/27.41/80.00 ms
MSS: 1440
Timeouts: 0

95%: ending the test
100%: test complete
```

I would have expected the `5%: geoip lookup` line to come close to `[!] cannot lookup asn: {cannot_open_geoip_database}`

**Comment by hellais** [comment]
It seems like this is something specific to the MK CLI https://github.com/measurement-kit/measurement-kit/blob/master/src/measurement_kit/utils.cpp#L15.

I would suggest you either write everything in measurement_kit CLI to stderr (that is unbuffered on most OSes I believe) or either set stdout to unbufferred  with `setbuf(stdout, NULL)` or just do a `flush(stdout)` every time you write (shouldn't be a problem since the output is not that much).

**Comment by bassosimone** [comment]
It should be fixed in master now. Thank you! :-)
