### ISSUE TITLE
Emit an event for report_id, probe_cc, probe_asn and probe_ip

### ISSUE THREAD

**Issue by hellais** [measurement-kit/measurement-kit#1461]
Currently there is no good way of learning the probe_cc, probe_asn, probe_ip and report_id without waiting for the `on_entry` callback to fire.

It would be useful if this information were emitted as an event.

**Comment by bassosimone** [comment]
Yes, I think this makes sense. In general, I'm in favor of adding more callbacks that help people using MK to learn about specific events occurring during the test. I think this can be done in v0.9.0.

**Comment by bassosimone** [comment]
Implemented in 2a49b966936cb77dfd1e6a1ba87a779cabdd2453
