### ISSUE TITLE
When an entry is not uploaded it should be reported to the caller

### ISSUE THREAD

**Issue by hellais** [measurement-kit/measurement-kit#1469]
Currently when I register a `on_entry` callback I have no way of knowing if that particular entry has been uploaded successfully or not.

I would like to know if the entry has been created and if not why it failed to be written.

Proposed API:

```
on_entry([](Error err, std::string &&entry)
```

**Comment by bassosimone** [comment]
This is now implemented in the new API, see d52e69c9990bee10cad6714b652f247d29bae5a0#diff-b0c6eef5a3fcf30ce59056ec52105749
