### ISSUE TITLE
Strip mobile specific metadata from HTTP responses

### ISSUE THREAD

**Issue by anadahz** [measurement-kit/measurement-kit#1473]
xref: https://github.com/ooni/probe/issues/780

Edit: fixed link

**Comment by hellais** [comment]
As discussed on slack, we don't want to go down the rabbit hole of enumerating all the possible headers that could contain PII. We are guaranteed to miss some (as they are operator specific) and we make it very clear that some of these can leak PII about the user.

If anything this is a good example of the sorts of things that we will be missing.

I am tempted to mark this as `wontfix`, but maybe we can keep it open in case somebody has a brilliant idea on how we can do this in a way that does not mean enumerating all the possible headers.
Maybe one option, could be to do it similar to the IP cleaning, where we search and replace the IMSI and MSISDN (the phone number of the user), but it seems like even on Android this call does not work well across different Android versions and in some versions it's missing according to: https://stackoverflow.com/a/2641218.
Do to this you probably also need some quite sketchy permissions (`android.permission.READ_PHONE_STATE`), which may be suboptimal.

**Comment by bassosimone** [comment]
Well, telling users whether their phone number is being leaked by mobile ISPs seems something that they would probably interested to know. Maybe we can enumerate the headers that we know to be problematic and add scrubbing for them only: wouldn't this be better than no scrubbing at all?

**Comment by darkk** [comment]
> To do this for the MSISDN

I'm actually unsure if that's reliable, AFAIK this API relies on "good will" of user / ISP writing their phone number to specific slot in SIM card address book. But I'm not a true mobile app developer.

**Comment by anadahz** [comment]
Since we know that HTTP headers leak IMSIs and phones numbers in OONI data we should make sure to address this issue in whatever way is technically feasible.

ISPs may be irresponsible or intentionally --_think of government owned ISPs_-- reveal personal identified data (such as users phone numbers) to the HTTP headers. We should make our best to communicate this to ooniprobe users, as (most probably) users may not know that they could potentially submit their phone numbers and IMSIs on public OONI data.

In light of this the [data policy](https://ooni.torproject.org/about/data-policy/#2-1-data-we-collect) should be updated (section "data we collect") to include potentially leaked IMSIs and phone numbers.

**Comment by hellais** [comment]
> Since we know that HTTP headers leak IMSIs and phones numbers in OONI data we should make sure to address this issue in whatever way is technically feasible.

I think this is well addressed inside of:
* https://github.com/measurement-kit/measurement-kit/issues/1476
* https://github.com/TheTorProject/ooni-pipeline/issues/105

> In light of this the data policy should be updated (section "data we collect") to include potentially leaked IMSIs and phone numbers

This is already stated in the section where we say:

> However, we might unintentionally collect your IP addresses and other personally-identifiable information if this data is included in the HTTP headers or other metadata of measurements

I would say this ticket can probably be considered superseeded by the solutions outlined in the two above tickets.

**Comment by anadahz** [comment]
> Since we know that HTTP headers leak IMSIs and phones numbers in OONI data we should make sure to address this issue in whatever way is technically feasible.
I think this is well addressed inside of:

>#1476
>TheTorProject/ooni-pipeline#105

I miss how the issue of sensitive data on HTTP headers is being addressed in any of the following tickets.

If I understand correctly the proposed test (in #1476) is about detecting possible sensitive HTTP headers not about redacting/removing the sensitive HTTP headers generated from other tests.
For this to happen (and please correct me if I'm wrong) the mobile applications need to force run this test prior to any other tests running and then redact/remove the HTTP headers found from the uploaded reports or introduce this testing methodology to all others tests.

The issue in TheTorProject/ooni-pipeline#105 will deal with reports that have been already submitted to the OONI collectors and contain sensitive HTTP headers.

**Comment by anadahz** [comment]
Adding some further mobile specific metadata found on measurements.

- [ ] `msisdn` (max 15 digits  https://en.wikipedia.org/wiki/MSISDN)

**Comment by bassosimone** [comment]
@hellais wrote:

> I think this is well addressed inside of:
>
> #1476
> ooni/backend#671

Yes. Closing this issue now. It duplicates other issues and more issues implies more distraction, more time spent understanding what to do, more confusion.
