### ISSUE TITLE
What is eof_error failure and when it occurs?

### ISSUE THREAD

**Issue by anadahz** [measurement-kit/measurement-kit#1474]
What is an `eof_error` failure and under which conditions it occurs?
I guess `eof` stands for end of file, any further explanation will help to debug potential issues with the device or the network.

OONI Reports examples, both on `ooniprobe-android` with version  `1.1.5`:
* https://explorer.ooni.torproject.org/measurement/20170922T024417Z_AS18881_LCncoChHEwmQalUy8aWSTIf0DUP5idhhUpRGquDyC16UWDlpQU
* https://explorer.ooni.torproject.org/measurement/20170922T024502Z_AS262872_OtPVa4wjtEzPmVZXwOiA4LXFozLnJELSgo4y35ZyFcnwNGsLRL

**Comment by bassosimone** [comment]
It means that, when you attempted to read from the socket expecting to read some bytes, you instead get zero bytes indicating that the connection was closed unexpectedly.

**Comment by anadahz** [comment]
Is this an issue of the network, device or both?

**Comment by bassosimone** [comment]
It's a network thing. The socket `recv` returns `0` in this case. It's up to developer whether to decide whether this "end of file" signal is acceptable in that moment or not.

(I closed the issue because I feel like I've answered the question.)

**Comment by anadahz** [comment]
> It's a network thing. The socket recv returns 0 in this case. It's up to developer whether to decide whether this "end of file" signal is acceptable in that moment or not.

How one should interpret such behavior (trying to understand what caused this issue)?

> (I closed the issue because I feel like I've answered the question.)

Sure I just asked as I haven't seen this anywhere in the documentation.

**Comment by bassosimone** [comment]
> How one should interpret such behavior (trying to understand what caused this issue)?

There was a middlebox which closed the connection when it did not see what it expected, perhaps.

Do you feel like that there is some field missing in the reports, BTW?

**Comment by anadahz** [comment]
Thank you.

> Do you feel like that there is some field missing in the reports, BTW?

Not sure if/which missing fields may have helped to debug this.
