### ISSUE TITLE
traceroute: import ios implementation

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/measurement-kit#1480]
Suggested by @willscott. [Repository](https://github.com/qiniu/iOS-netdiag) (MIT license) we can use as the starting point (but I think we'll rewrite the concept to fit our traceroute model and to be C++14).

**Comment by hellais** [comment]
Added it to the #1421 epic

**Comment by bassosimone** [comment]
> Added it to the #1421 epic

Thanks!

**Comment by darkk** [comment]
xref: #683

**Comment by hellais** [comment]
Other possible implementation to look at:

* https://github.com/bryanyuan/Traceroute
* https://github.com/brbulic/TracerouteTester
* https://github.com/ivoryxiong/IVYTraceroute

**Comment by bassosimone** [comment]
Thanks!

**Comment by bassosimone** [comment]
Flagging this as research. We probably need to understand whether we should implement this functionality in Go or rather use MK and C/C++ code for that.

**Comment by bassosimone** [comment]
https://github.com/ooni/probe-engine/issues/46
