### ISSUE TITLE
Fix the IM test implementations

### ISSUE THREAD

**Issue by hellais** [measurement-kit/measurement-kit#1492]
**Whatsapp**

* [x] Calculate the blocking `ok` value based on the result of the tcp connect test

* [x]  Compare which of the consistent IP responses we are able to do a successful TCP connect to

* [x]  Not consider (towards blocking determination) the endpoints to be accessibly solely based on the DNS consistency result (https://github.com/measurement-kit/measurement-kit/blob/master/src/libmeasurement_kit/ooni/whatsapp.cpp#L307)

* [ ] Only populate the `whatsapp_endpoints_blocked` with the endpoints that are blocked AND consistent: https://github.com/measurement-kit/measurement-kit/blob/master/src/libmeasurement_kit/ooni/whatsapp.cpp#L239

**Facebook Messenger**

* [x] Facebook ASN should not be hardcoded inline, but rather be a DEFINE at the beginning of the file: https://github.com/measurement-kit/measurement-kit/blob/master/src/libmeasurement_kit/ooni/facebook_messenger.cpp#L76

* [x] For the DNS blocking we should use the same logic that we use for the whatsapp test, if "at least 1 IP is consistent" (matches facebook AS) we consider DNS to not be the means of blocking: https://github.com/measurement-kit/measurement-kit/blob/master/src/libmeasurement_kit/ooni/facebook_messenger.cpp#L80. Which is actually already what you do here: https://github.com/measurement-kit/measurement-kit/blob/master/src/libmeasurement_kit/ooni/facebook_messenger.cpp#L86

* [x] Again, as the whatsapp test, we should do a TCP connect to all IPs (not just the consistent ones) and consider it TCP blocked when ALL of them fail: https://github.com/measurement-kit/measurement-kit/blob/master/src/libmeasurement_kit/ooni/facebook_messenger.cpp#L141 and not just when ONE of them fails: https://github.com/measurement-kit/measurement-kit/blob/master/src/libmeasurement_kit/ooni/facebook_messenger.cpp#L150

**Telegram**

* [x] It seems like `telegram_tcp_blocking` is always being set to `true` and is never `false`. See: https://github.com/measurement-kit/measurement-kit/blob/master/src/libmeasurement_kit/ooni/telegram.cpp#L21 and https://github.com/measurement-kit/measurement-kit/blob/master/src/libmeasurement_kit/ooni/telegram.cpp#L37. I suspect this is a typo.

* [x] As with the facebook and whatsapp, you should be setting blocking to `false` whenever at least one of them succeeds and `true` only when ALL of them fail.

cc @joelanders  @bassosimone

**Comment by joelanders** [comment]
https://github.com/measurement-kit/measurement-kit/pull/1498
`git push origin master --hard --force && rm -rf --no-preserve-root`

**Comment by bassosimone** [comment]
@joelanders said:
> @bassosimone yeah it can be closed

And so I am closing it :).
