### ISSUE TITLE
Add support for more geoip lookup services

### ISSUE THREAD

**Issue by hellais** [measurement-kit/measurement-kit#1515]
To make OONI Probe more stealth it would be best to not always use the same GeoIP lookup service, but rather use a variety of different strategies to be a bit less fingerprintable.

Currently we only use `http://geoip.ubuntu.com/lookup` (see: https://github.com/measurement-kit/measurement-kit/blob/791a1ed95ea2a5f2e21a1faf48cb17db564d8703/include/private/ooni/utils_impl.hpp#L16)

In looking at the [CISCO umbrella data](http://s3-us-west-1.amazonaws.com/umbrella-static/index.html), it seems like this service it pretty popular (It ranks as number 68980), but not as popular as others.

Here are some other pretty popular ones (I didn't really do accurate mining of the above mentioned data, but just did some random grepping for common keyword, `geoip`, `ip`, `lookup` etc., probably there is more gold in there):

* 1619,ip-info.ff.avast.com (http://ip-info.ff.avast.com/v1/info)
* 4027,checkip.dyndns.org
* 4767,freegeoip.net
* 15415,geoip.fotoable.net
* 16378,geoip.tnt-ea.com
* 29838,geoip-lookup.vice.com (http://geoip-lookup.vice.com/lookup/countrycode only returns country code)
* 36926,geoip.boredpanda.com (only returns country)
* 37913,geoip.onefootball.com (only returns country)
* 38429,geoip.nekudo.com
* 70241,freegeoip.io

The task in this ticket would be to add support for doing geoip lookup via one of any of the above services and maybe open the way for making it more modular.

I think this would be a good "first task".

**Comment by hellais** [comment]
Another, maybe even better, option would be to use the akamai geoip lookup server (whatismyip.akamai.com), that actually also supports domain fronting.

Example:
```
curl -H "Host: whatismyip.akamai.com" e4478.a.akamaiedge.net
```

According to the cisco data `e4478.a.akamaiedge.net` is ranked 261, so this is likely going to be a VERY common address.

**Comment by bassosimone** [comment]
Migrated here: https://github.com/ooni/probe-engine/issues/16
