### ISSUE TITLE
Add support for using the /collectors & /test-helpers proteus endpoints

### ISSUE THREAD

**Issue by hellais** [measurement-kit/measurement-kit#1537]
We have recently added support to, but not yet deployed, to the orchestration backend for:

* Discovering the collector `/collectors` (https://github.com/TheTorProject/proteus/blob/master/docs/orchestrate-swagger.yml#L140)
* Discovering test helper addresses `/test-helpers` (https://github.com/TheTorProject/proteus/blob/master/docs/orchestrate-swagger.yml#L122)

These are all we need to replace the bouncer API.

I am thinking of implementing a thing compatibility layer between these two endpoints and the legacy bouncer, but I think eventually measurement-kit should support the more modern approach.

**Comment by bassosimone** [comment]
My understanding is that the new API implementation will still support the old APIs, therefore I think this is something that should be implemented on a best effort basis, since it's not urgent.

**Comment by bassosimone** [comment]
The ooni/probe-engine code does that. This won't be implemented in MK.
