### ISSUE TITLE
Add support for fetching URL lists from proteus

### ISSUE THREAD

**Issue by hellais** [measurement-kit/measurement-kit#1538]
We have recently added support to proteus (but not yet deployed) for listing URLs.

See: https://github.com/TheTorProject/proteus/blob/master/docs/orchestrate-swagger.yml#L95, the `/urls` endpoint.

We should add support to MK for fetching URLs in this way. It should be possible from the MK API to specify what is the country, the desired categories and the URL count.

This should superseed having static URL lists.

**Comment by bassosimone** [comment]
My understanding is that the new API implementation will still support the old APIs, therefore I think this is something that should be implemented on a best effort basis, since it's not urgent.

**Comment by bassosimone** [comment]
The ooni/probe-engine code does that. This won't be implemented in MK.
