### ISSUE TITLE
Add support for opportunistically switching over to domain fronting

### ISSUE THREAD

**Issue by hellais** [measurement-kit/measurement-kit#1539]
We have many requests that rely on certain OONI domains not being blocked.

It would be neat if MK would figure out that a OONI service is blocked and when some option is enabled, do a retry on the domain fronted equivalent.

I am actually also fine with having this logic live in the apps themselves (OONI Probe), but maybe if it's not too much effort it could all be done in MK.

**Comment by bassosimone** [comment]
I will need to think about this. I generally tend to see MK as the engine and the app as the driver. But perhaps there can be a setting, defaulting to `false`, where one can request for this behavior. I think we need to spend some time thinking about what the algorithm would look like.

**Comment by bassosimone** [comment]
Will be done in https://github.com/ooni/probe-engine/issues/19
