### ISSUE TITLE
MK crashing when given a path with spaces

### ISSUE THREAD

**Issue by lorenzoPrimi** [measurement-kit/measurement-kit#1550]
When the PRODUCT_NAME was changed from `ooniprobe` to `OONI Probe` on iOS mk crashed with error
`libc++abi.dylib: terminating with uncaught exception of type mk::ValueError: value_error`
When investigating on the bug it is because it contains a space in the geoip path
`/Users/lorenzo/Library/Developer/CoreSimulator/Devices/0E1A6577-5564-458E-B037-1C389566401F/data/Containers/Bundle/Application/D9F41C26-934C-41F1-9AF8-459063FD00DC/OONI Probe.app/GeoIPASNum.dat`

**Comment by bassosimone** [comment]
Thanks for reporting this! I've [sketched out a fix for this in the new API](https://github.com/measurement-kit/measurement-kit/pull/1555/commits/9e321624ea8e300eb66c73cc3ca5a62a24950fcf). So, when #1555 is merged and the new API is used, this problem would go away. Still, I believe more work is needed to fix the issue further down the chain in the place where it originates (the `SettingsEntry` class).
