### ISSUE TITLE
DNS engine=system reports TTL=0

### ISSUE THREAD

**Issue by darkk** [measurement-kit/measurement-kit#1556]
TTL=0 is a valid TTL value for DNS packet. Yes, [it's bad idea to have TTL=0](http://mark.lindsey.name/2009/03/never-use-dns-ttl-of-zero-0.html), but seems [there are packets like that](https://00f.net/2011/11/17/how-long-does-a-dns-ttl-last/). I think, the statement may be verified if it matters.

Anyway, there are reports claiming TTL=0 for engine=system while this engine does not support TTL at all. Affected version are 0.7.6 and 0.8.1.
```
  "test_keys": {
    "queries": [
      {
        "engine": "system",
        "resolver_hostname": null,
        "query_type": "A",
        "hostname": "www.rutracker.org",
        "answers": [
          {
            "ipv4": "88.208.38.202",
            "answer_type": "A",
            "ttl": 0
          }
        ],
        "failure": null,
        "resolver_port": null
      }
    ],
  },
```

I suggest to omit `ttl` field if it's not known. Having a sentinel value is a bad idea as any UINT32 value is a valid TTL value (but resolvers may enforce min/max TTL). Try `dig $(( 0xffffffff )).42.rnd.darkk.net.ru @rnd-zone.darkk.net.ru` :)

**Comment by bassosimone** [comment]
You're right. In general the `getaddrinfo` DNS engine returns very little info. I think this can be addressed by trimming down the amount of info returned when the engine is that.

Thanks for pointing this out to me.

**Comment by bassosimone** [comment]
I've sketched out a solution for this in #1558.
