### ISSUE TITLE
Improve captive portal test

### ISSUE THREAD

**Issue by hellais** [measurement-kit/measurement-kit#1577]
The current captive portal test is missing some features from the original OONI Probe test.

I think before we have it exposed to end users it should at least:

* Implement 0x20 check
* Implement google_dns_cp test

I think how the w3 captive portal test was done, was actually wrong. The status code it checks for is deprecated and we should be checking for https://tools.ietf.org/html/rfc6585#section-6 instead.

**Comment by bassosimone** [comment]
Won't happen. We'll instead work on a Go implementation. See https://github.com/ooni/probe-engine/issues/40.
