### ISSUE TITLE
Switch to using maxmind GeoLite2

### ISSUE THREAD

**Issue by hellais** [measurement-kit/measurement-kit#1580]
As per: https://dev.maxmind.com/geoip/geoip2/geolite2/

> As of April 1, 2018, updated versions of the GeoLite Legacy databases will be available to redistribution license customers only, although anyone can continue to download the March 2018 GeoLite Legacy builds. On January 2, 2019, the last build will be removed from our website. GeoLite Legacy database users will need to switch to the GeoLite2 or commercial GeoIP databases and update their integrations by January 2, 2019.

td;dr we should switch to using the geolite2 database files for new releases of measurement-kit.

This means:

1. Updating the code to use the new format (and the new library for maxmind: https://github.com/maxmind/libmaxminddb)
2. Updating the mobile apps to ship the new maxmind database format

It seems like this is already packaged in ubuntu: https://packages.ubuntu.com/xenial/libdevel/libmaxminddb-dev and homebrew: http://brewformulas.org/Libmaxminddb

**Comment by bassosimone** [comment]
[Measurement-kit/mkgeoip](https://github.com/measurement-kit/mkgeoip), included in MK v0.9.0-alpha.10, has this functionality. We need to migrate the rest of the code over.

**Comment by bassosimone** [comment]
This has been merge to master.
