### ISSUE TITLE
Test list for tcp / VPN connectivity

### ISSUE THREAD

**Issue by willscott** [measurement-kit/measurement-kit#1581]
There is a TCP connectivity test, and thoughts on a number of VPN protocols that could be interesting, e.g. https://github.com/measurement-kit/measurement-kit/issues/1418

However, in addition to these tests, we may need an input generation like exists for web_connectivity.

This is spurred by riseup.net being interested in having their vpn connectivity tested, but tunnelbear listed in the previous bug is another case, as would be tor bridges / dirauth's.

**Comment by bassosimone** [comment]
Migrated https://github.com/ooni/probe-engine/issues/45
