### ISSUE TITLE
UTF-8 characters in filepaths for GeoIP database files are not supported on windows

### ISSUE THREAD

**Issue by hellais** [measurement-kit/measurement-kit#1635]
I ran into this issue while trying to get OONI Probe working on windows. In particular I ran into problems with the GeoIP database files not being found, though I had specified a valid path.

The root cause of the problem appears to be the `fopen` call that the maxmind geoip library is making, which on windows only supports ansi characters. See: https://github.com/maxmind/geoip-api-c/blob/master/libGeoIP/GeoIP.c#L1638.

I also looked at the new version of the maxmind database and it seems to also have the same issue: https://github.com/maxmind/libmaxminddb/blob/master/src/maxminddb.c#L330.

The fix to this issue should probably be of upstreaming a patch to maxmind that will call the correct function and checking that it works properly or maybe there is a way to pass to maxmind an already open handle where we open the file ourselves.

Links I found useful are:
- https://stackoverflow.com/questions/396567/is-there-a-standard-way-to-do-an-fopen-with-a-unicode-string-file-path
- http://www.osronline.com/showThread.cfm?link=20658

**Comment by bassosimone** [comment]
As a workaround, I recommend trying to run in `$OONI_HOME`, so to avoid to deal with full paths that may contain UTF-8 characters. IIRC, on Windows there are two options: ANSI and UTF-16. Compiling code as UTF-16 may break lots of places in MK, so this needs to be done with care. When we were serious about touching the file system, I remember I wanted to use a portable library such as apache's apr, to deal with the Windows/Unix file system differences in the most easy way (for us). It may be that a lighter approach is to understand how to properly compile dependencies and/or to submit patches upstream to get the desired behavior.

**Comment by bassosimone** [comment]
I think we can close this issue now, as @hellais has found the fix that entailed the least amount of complexity (and of possible unexpected future bugs) for us all. Thanks!
