### ISSUE TITLE
whatsapp all_endpoints broken in v0.9.0

### ISSUE THREAD

**Issue by lorenzoPrimi** [measurement-kit/measurement-kit#1654]
These parameters are missing:
"server", "port" for ndt and dash
"all_endpoints" for whatsapp

**Comment by bassosimone** [comment]
Not critical for a release.

**Comment by bassosimone** [comment]
How is not changing the documentation an issue for the mobile apps?

**Comment by lorenzoPrimi** [comment]
Sorry, I thought these options were not handeled by mk at all.

**Comment by bassosimone** [comment]
I believe they are. Can you perhaps confirm? It required a little bit of refactoring to update the docs, so I decided to postpone it after release. However, if all endpoints is not working, then this is an issue to be fixed!

**Comment by bassosimone** [comment]
So, it seems they don’t work. But then it’s not a documentation issue, rather I need to change engine.cpp. Thanks for bringing this issue to my attention, I think this will go in v0.9.1.

**Comment by bassosimone** [comment]
Merged in both master and stable
