### ISSUE TITLE
Considerations around privacy settings

### ISSUE THREAD

**Issue by hellais** [measurement-kit/measurement-kit#1655]
Currently MK will return the empty string both in the case of a failure ip resolution, but also if the user has opted out to collect their IP.

We should evaluate if this is a good pattern and if we ought to not have the logic of stripping the IP inside of the app itself and return the null string only in case of failure.

**Comment by bassosimone** [comment]
See also #1435

**Comment by bassosimone** [comment]
So, the code has changed in `v0.9.0-beta` as follows. Relevant failure events are emitted if any of the GeoIP lookup phases fail. The message passed from MK to the app always contains all the information that was looked up, regardless of privacy settings. The report uploaded to the OONI collector, instead, honours the privacy settings. Information for which we do not have privacy settings do not escape the scope of the specific method in which they are computed. This IMHO addresses the original concern that was expressed when opening this ticket. Closing this ticket now.
