### ISSUE TITLE
Make geolocation API sync

### ISSUE THREAD

**Issue by hellais** [measurement-kit/measurement-kit#1656]
It would be great if the MK API supported doing a geoip resolution outside of the testing logic.

This would allow a user, for example, to call https://github.com/measurement-kit/measurement-kit/issues/1538 with the country code of the user independently from the testing logic.

**Comment by bassosimone** [comment]
Yeah, I think this is a good idea. Thanks for pointing this out.

**Comment by bassosimone** [comment]
@hellais I have a question regarding this use case: what is the input? Is the input an already known IP address, or there is no input and you want to also discover the IP address. Asking because the latter functionality is actually already part of MK, while the former is not. Discussing the former functionality begs the question of how the app is going to discover its IP address.

**Comment by lorenzoPrimi** [comment]
This already exists https://github.com/measurement-kit/measurement-kit/blob/master/include/measurement_kit/ooni/utils.hpp
Has to be made sync

**Comment by lorenzoPrimi** [comment]
Ideally the events.proteus.test.ooni.io server should do the country resolving if country_code is not set.
Even because server side the GeoIP files can be updated in a faster way without waiting for a new app release.
In the 2.1 we might use GPS.

**Comment by lorenzoPrimi** [comment]
Linked to https://github.com/ooni/orchestra/issues/49

**Comment by bassosimone** [comment]
Added the "critical" flag because this is key to make OONI 2.0.0-beta.

**Comment by bassosimone** [comment]
Changed the title. We already have an API for that. What we actually need here is to expose a sync API rather than an asynchronous API.

**Comment by bassosimone** [comment]
This is included in MK v0.9.0-alpha.10 via [measurement-kit/mkgeoip](https://github.com/measurement-kit/mkgeoip), which will have a ObjectiveC and Java APIs.
