### ISSUE TITLE
orchestration: possibility to send a flag when the user enable notification on news

### ISSUE THREAD

**Issue by lorenzoPrimi** [measurement-kit/measurement-kit#1668]
This is critical for the release of v2.0.0 of OONI mobile.

**Comment by lorenzoPrimi** [comment]
@hellais do we need this in 2.0? send a flag when the user enable notification on news?

**Comment by hellais** [comment]
> @hellais do we need this in 2.0? send a flag when the user enable notification on news?

I would suggest we push this to 2.1 since we don't have the New feed tab yet. I also suggest we remove the option from the settings.

**Comment by lorenzoPrimi** [comment]
Agreed.

**Comment by bassosimone** [comment]
Superseded by https://github.com/ooni/probe-engine/issues/15
