### ISSUE TITLE
Avoid using "/" in var names in Settings

### ISSUE THREAD

**Issue by lorenzoPrimi** [measurement-kit/measurement-kit#1676]
I have a problem when serializing settings in Objective-c, my Settings/Option class is automatically mapped into NSDictionary (or json string) and the keys are the variables names:
https://github.com/ooni/probe-ios/blob/release/2.0.0/ooniprobe/Settings/Options.h

Now as I can't use `/` into a variable name i need to manually change `net/ca_bundle_path` with `ca_bundle_path` as you can see here
https://github.com/ooni/probe-ios/blob/release/2.0.0/ooniprobe/Model/Settings/Settings.m#L37

**Comment by bassosimone** [comment]
This is basically an issue with the data format used by MK. If possible, I'd double check whether it's possible to fore the name used to serialise a field. If forcing the fields name to serialise is not possible, I am open to change the data format used for the settings in the v0.10 cycle.

**Comment by lorenzoPrimi** [comment]
It is possible to force field to serialise with another name on Android.
On iOS now I used an hack, probably wouldn't be difficult to map it with this library, I have to check the doc in deep https://github.com/aryaxt/OCMapper

**Comment by lorenzoPrimi** [comment]
fixed iOS side here : https://github.com/ooni/probe-ios/commit/71ed0148c54b594638b44fde85fc4d83c9ce0c4b

**Comment by bassosimone** [comment]
Okay, but I guess we still want to fix this also in MK aim a future release, no?

**Comment by lorenzoPrimi** [comment]
It's not a bug anymore as we have native options in iOS and Android to separate the variable name from the serialized name.

**Comment by bassosimone** [comment]
I believe it’s still weird / surprising

**Comment by bassosimone** [comment]
Let's not mess with the existing API. We've found workarounds everywhere we use MK.
