### ISSUE TITLE
script-build-unix/ios: force autoconf not to find timingsafe_bcmp et al.

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/measurement-kit#1687]
xref: https://github.com/measurement-kit/script-build-unix/issues/7

**Comment by bassosimone** [comment]
So, to better understand this issue, I've re-run LibreSSL `./configure` script (in script-build-unix) to see what is the output _for all architectures_. This is important to understand whether the issue only happens on specific architectures or is present _across all_ architectures.

```
$ grep -Rn timingsafe_bcmp LOG*.txt
LOG.arm64.txt:189:checking for timingsafe_bcmp... yes
LOG.armv7s.txt:189:checking for timingsafe_bcmp... yes
LOG.i386.txt:189:checking for timingsafe_bcmp... yes
LOG.x86_64.txt:189:checking for timingsafe_bcmp... yes
```

Now, `timingsafe_bcmp` is defined in `string.h`. Let's see how the `string.h` looks like for the iPhoneOS and iPhoneSimulator development platforms. These are the headers to look into:

```
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/string.h
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/include/string.h
```

The iPhoneOS `string.h` defines `timingsafe_bcmp` as:

```
__OSX_AVAILABLE(10.12.1) __IOS_AVAILABLE(10.1)
__TVOS_AVAILABLE(10.0.1) __WATCHOS_AVAILABLE(3.1)
int     timingsafe_bcmp(const void *__b1, const void *__b2, size_t __len);
__END_DECLS
```

The iPhoneSimulator `string.h` as:

```
__OSX_AVAILABLE(10.12.1) __IOS_AVAILABLE(10.1)
__TVOS_AVAILABLE(10.0.1) __WATCHOS_AVAILABLE(3.1)
int     timingsafe_bcmp(const void *__b1, const void *__b2, size_t __len);
__END_DECLS
```

From this, we can conclude that the build process is not correctly telling Xcode that we want to target iOS 9 as minimum version of iOS (both for simulator and devices) &mdash; dammit!

**Comment by bassosimone** [comment]
Next step of the investigation is to look into `CFLAGS`. They should be in effect when we're checking and they should condition the version of `iOS` that Xcode thinks we're targeting.

```
$ ./cross-ios armv7s|grep CFLAGS
CFLAGS=-O2 -arch armv7s -miphoneos-version-min=9.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk
```

So, we're setting a flag indicating the minimum version. Now, we need to understand whether configure is _using_ this flag when checking for `timingsafe_bcmp`.

```
$ ./cross-ios armv7s ./libressl
... [wait after ./configure and then ^C]
$ less MK_BUILD/ios/libressl/2.8.2-0.1.1+2/armv7s/libressl-2.8.2/config.log
```

What we see is the following (sorry for the long line):

```
configure:13882: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -o conftest -O2 -arch armv7s -miphoneos-version-min=9.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk  -Wall -std=gnu99 -fno-strict-aliasing  -fno-strict-overflow -D_FORTIFY_SOURCE=2 -fstack-protector-strong  -Qunused-arguments -Wno-pointer-sign -arch armv7s -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk -DMK_NO_THREAD_LOCAL  -arch armv7s -miphoneos-version-min=9.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk   -Qunused-arguments conftest.c  >&5
```

So, apart from the fact that `CPPFLAGS` and `CFLAGS` duplicate many flags, it seems we're passing the flag down to `./configure` correctly. This begs the question of whether it's the right flag.

The `clang(1)` entry on macOS looks like this:

```
       -miphoneos-version-min
              When building for iPhone OS, specify the minimum version supported by
              your application.
```

So, that seems to be the correct flag. Mumble mumble.

**Comment by bassosimone** [comment]
So, here's an interesting (and confusing) experiment:

```
$ cat xx.h
#include <Availability.h>

#include <stdlib.h>

__IOS_AVAILABLE(10.1)
int     timingsafe_bcmp(const void *__b1, const void *__b2, size_t __len);
$ cat xx.c 
#include "xx.h"

int main() {
  timingsafe_bcmp(0, 0, 0);
}
$ /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -arch armv7s -miphoneos-version-min=9.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk xx.c 
$
```

Why is this code compiling? From the TIL department: I _thought_ that `-miphoneos-version-min=9.0` meant that the definition was _masked_ in headers when using an iOS version greater than `9.0`. [It turns out](https://github.com/golang/go/issues/16770), instead, that _weak linking_ is used for all symbols introduced after `9.0`.

The fix seems to be to pass `-Wl,-no_weak_imports` to the linker, to make linking fail if the symbol was not present in the target version of iOS (in this case `9.0`). Let's see:

```
$ /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -arch armv7s -miphoneos-version-min=9.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk -Wl,-no_weak_imports xx.c 
ld: weak import of symbol '_timingsafe_bcmp' not supported because of option: -no_weak_imports for architecture armv7s
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Okay, so now we understand the issue. Let's try and pass `-Wl,-no_weak_imports` to the linker and rerun the configure script of LibreSSL to see if it now skips `timingsafe_bcmp`.

**Comment by bassosimone** [comment]
So, this is also unexpected. If I apply the fix:

```
diff --git a/cross-ios b/cross-ios
index e4246c9..1050e34 100755
--- a/cross-ios
+++ b/cross-ios
@@ -34,7 +34,7 @@ export CXX="$(xcrun -find -sdk ${PLATFORM} g++)"
 export CPPFLAGS="-arch ${PKG_ARCH} -isysroot $(xcrun -sdk ${PLATFORM} --show-sdk-path) $EXTRA_CPPFLAGS $CPPFLAGS"
 export CFLAGS="-O2 -arch ${PKG_ARCH} $MINVERSION -isysroot $(xcrun -sdk ${PLATFORM} --show-sdk-path) $CFLAGS"
 export CXXFLAGS="-O2 -arch ${PKG_ARCH} $MINVERSION -isysroot $(xcrun -sdk ${PLATFORM} --show-sdk-path) $CXXFLAGS"
-export LDFLAGS="-arch ${PKG_ARCH} $MINVERSION -isysroot $(xcrun -sdk ${PLATFORM} --show-sdk-path) $LDFLAGS"
+export LDFLAGS="-arch ${PKG_ARCH} $MINVERSION -isysroot $(xcrun -sdk ${PLATFORM} --show-sdk-path) -Wl,-no_weak_imports $LDFLAGS"
 export PKG_CONFIGUREFLAGS
 export PKG_OS="ios"
 export PKG_ARCH
```

and run `./configure` again:

```
./cross-ios armv7s ./libressl
```

I see in `config.log` the following:

```
configure:13882: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -o conftest -O2 -arch armv7s -miphoneos-version-min=9.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk  -Wall -std=gnu99 -fno-strict-aliasing  -fno-strict-overflow -D_FORTIFY_SOURCE=2 -fstack-protector-strong  -Qunused-arguments -Wno-pointer-sign -arch armv7s -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk -DMK_NO_THREAD_LOCAL  -arch armv7s -miphoneos-version-min=9.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk -Wl,-no_weak_imports   -Qunused-arguments conftest.c  >&5
configure:13882: $? = 0
configure:13882: result: yes
```

Where I see `-miphoneos-version-min=9.0` and `-Wl,-no_weak_imports`. However, it's not failing as expected, it's instead working correctly. Now, the question is: why?

**Comment by bassosimone** [comment]
A-ha, so, here's a minimal example explaining the issue. Let's set the environment up (this time I'm trying to use `xcrun` so to make the example much more readable):

```
$ export CPPFLAGS="-isysroot `xcrun -sdk iphoneos --show-sdk-path`"
$ export CFLAGS="-arch armv7s -miphoneos-version-min=9.0"
$ export LDFLAGS="-Wl,-no_weak_imports"
```

Now, let's first run the check as GNU autoconf would run it:

```
$ cat test.c 
char timingsafe_bcmp ();
int main() {
  return timingsafe_bcmp();
}
$ cc $CPPFLAGS $CFLAGS $LDFLAGS test.c 
$ echo $?
0
```

It works. Weird, eh. Now let's just try to _annotate_ `timingsafe_bcmp` as available since iOS 10.1 (without event bothering with providing the correct prototype).

```
$ cat test.c 
#include <Availability.h>
__IOS_AVAILABLE(10.1) char timingsafe_bcmp ();
int main() {
  return timingsafe_bcmp();
}
$ cc $CPPFLAGS $CFLAGS $LDFLAGS test.c 
ld: weak import of symbol '_timingsafe_bcmp' not supported because of option: -no_weak_imports for architecture armv7s
clang: error: linker command failed with exit code 1 (use -v to see invocation)
$ echo $?
1
```

Boom. It seems the way in which Apple declares stuff as available or not available (i.e. using an explicit annotation in the header) conflicts with the way in which GNU autoconf checks for a function being available or not, i.e. by _not_ including any specific header. This does not make me very happy.

**Comment by bassosimone** [comment]
For comparison, what Android does is the following:

```
#if __ANDROID_API__ >= 28
int getentropy(void* __buffer, size_t __buffer_size) __wur __INTRODUCED_IN(28);
#endif
```

I actually find this a better approach, because it _hides_ the symbol from the preprocessor, and so the checking technique implemented by GNU autotools works better there.

**Comment by bassosimone** [comment]
The related homebrew issue is https://github.com/Homebrew/homebrew-core/issues/3727

**Comment by bassosimone** [comment]
I believe this issue should not prevent us from making v0.9.1. I will further investigate and possibly open a bug with Apple or LibreSSL next week. We want instead v0.9.2 out ASAP.

So, I've created a v0.9.2 release and will assign this issue to that. If we end up not making v0.9.2, then this issue will instead be assigned to v0.10.0.

**Comment by bassosimone** [comment]
Just FTR, this issue is also present in iOS 10.0 (just installed the simulator and tried)

**Comment by achivetta** [comment]
Those special symbols mentioned in point 2 were only added on macOS.  For iOS, you'll likely need to force autoconf's hand somehow.

**Comment by bassosimone** [comment]
Thanks a bunch for the clarification, @achivetta, really appreciated!

**Comment by bassosimone** [comment]
@achivetta, still, I don't understand how this is supposed to work on macOS. That is, I cannot cause the compilation to fail _even when compiling from macOS_. A minimal example follows:

`Timingsafe_bcmp` should be available from macOS 10.11 onwards:

```
$ grep timingsafe_bcmp /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/system/libsystem_c.tbd 
                       '$ld$weak$os10.11$_timingsafe_bcmp', '$ld$weak$os10.12$_utimensat', 
                       _timeoff, _times, _timezone, _timingsafe_bcmp, _tmpfile, _tmpnam,
```

However:

```
$ clang -v -Wall -Wextra -Wl,-no_weak_imports -mmacosx-version-min=10.9 main.c 
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
 "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang" -cc1 -triple x86_64-apple-macosx10.9.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name main.c -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -fno-strict-return -masm-verbose -munwind-tables -faligned-alloc-unavailable -target-cpu core2 -dwarf-column-info -debugger-tuning=lldb -target-linker-version 409.12 -v -resource-dir /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.0 -Wall -Wextra -fdebug-compilation-dir /tmp/xyz -ferror-limit 19 -fmessage-length 93 -stack-protector 1 -fblocks -fencode-extended-block-signature -fobjc-runtime=macosx-10.9.0 -fmax-type-align=16 -fdiagnostics-show-option -fcolor-diagnostics -o /var/folders/bl/r84rmchd6c5848k6gxvvky_m0000gn/T/main-ef86bb.o -x c main.c
[...]
 "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld" -demangle -lto_library /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libLTO.dylib -no_deduplicate -dynamic -arch x86_64 -macosx_version_min 10.9.0 -o a.out -no_weak_imports /var/folders/bl/r84rmchd6c5848k6gxvvky_m0000gn/T/main-ef86bb.o -lSystem /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.0/lib/darwin/libclang_rt.osx.a
$ echo $?
0
```

Where:

```
$ cat main.c 
char timingsafe_bcmp ();
int main() {
  return timingsafe_bcmp();
}
```

Shouldn't `.../ld -macosx_version_min 10.9.0 -no_weak_imports` fail, given that `$ld$weak$os10.11$_timingsafe_bcmp` is in `libsystem_c.tbd`?

Am I missing something obvious here? Are my assumptions wrong?

**Comment by bassosimone** [comment]
> [...] you'll likely need to force autoconf's hand somehow.

The correct way of doing that is to perform:

```bash
export ac_cv_func_timingsafe_bcmp=no
```

before running `./configure`. With this change, we get:

```
$ ./configure
[...]
checking for timingsafe_bcmp... (cached) no
```

This causes the build system to compile and link a `timingsafe_bcmp` function. Doing that, even on systems whose `libc` has `timingsafe_bcmp` is okay, because the net effect is just that we statically link a definition of `timingsafe_bcmp` into the `libcrypto.a` generated by LibreSSL.

However, doing that does not fully solve our problem:

1. there are likely other functions for which the same problem exists, so we should make sure that we also force autoconf for these functions as well (which is a bit error prone)

2. I am _also_ wondering whether we have the same issue on Android.

**Comment by bassosimone** [comment]
Since there's no issue on Android and only old versions of iOS are affected, and Apple aggressively tries to push new iOS versions to users, I am going to (1) open a bug report for `ld` with Apple; (2) not rush a bugfix for v0.9.2 but rather schedule fixing this issue for v0.10.0.

**Comment by bassosimone** [comment]
Empirically, we've not seen any crash related to this issue in Fabric. Nor we have been reported about this kind of issue by anyone. I think it's fair to assume this issue exists and mainly pertains to old iOS versions. As such, I feel comfortable with pushing this further down the line and focusing on other issues that are iOS related and require much more of my immediate attention.

**Comment by bassosimone** [comment]
We can close this issue because https://github.com/measurement-kit/script-build-unix/issues/7 is now tracked by https://github.com/orgs/measurement-kit/projects/1
