### ISSUE TITLE
Use mkall-ios on iOS

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/measurement-kit#1691]
This is about using [mkall-ios](https://github.com/measurement-kit/mkall-ios) in OONI probe for iOS. We've made progress with @lorenzoPrimi and it may even happen that we can land this in v0.9.1.

**Comment by bassosimone** [comment]
@lorenzoPrimi good to know! Then I need to make a pod out of it.

**Comment by lorenzoPrimi** [comment]
To finish the implementation I'm waiting for:
https://github.com/measurement-kit/measurement-kit/issues/1688 [DONE]
https://github.com/measurement-kit/measurement-kit/issues/1685
https://github.com/measurement-kit/measurement-kit/issues/1702
https://github.com/measurement-kit/measurement-kit/issues/1703

**Comment by bassosimone** [comment]
I have implemented this in ooni/probe-ios#199. When @lorenzoPrimi confirms that all is good, I believe we can close this issue and focus on something else.

**Comment by lorenzoPrimi** [comment]
#1688 [DONE]
#1685 [Still problems]
#1702 [Waiting next mkall-ios release]
#1703 [DONE]

**Comment by bassosimone** [comment]
So, this is now done. It’s a bit unclear why this issue was used to track other unrelated issues. I recommend using projects for this purpose (see the v0.9.1 project that conveys exactly the same info as above using a Kanban board)

**Comment by lorenzoPrimi** [comment]
Because until everything is working fine I won't merge https://github.com/ooni/probe-ios/pull/198

**Comment by bassosimone** [comment]
Yeah but I fail to see why you’re using an unrelated issue to track progress

**Comment by bassosimone** [comment]
I would encourage you to either use the MK v0.9.1 to see how MK progresses or a specific kanban board for mobile apps in the OONI GitHub organisation
