### ISSUE TITLE
Get rid of randomize_inputs option

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/measurement-kit#1697]
Mobile apps don't use it. Desktop apps don't use it. It's now become optional complexity.

I'll get rid of this unless @hellais and/or @lorenzoPrimi have strong opinions against this move, like that there is a plan that I do not foresee for using this functionality soon.

**Comment by hellais** [comment]
I agree with this idea. I think that if software using MK needs to randomize inputs, they can do it themselves and pass a randomized list to MK.

**Comment by bassosimone** [comment]
Excellent, thanks!

**Comment by bassosimone** [comment]
As part of fixing this issue, it's also important to warn that the specified setting is not available anymore.

**Comment by bassosimone** [comment]
Postponing to v0.11.0.

**Comment by bassosimone** [comment]
Let's not mess with the existing API at this point. With https://github.com/ooni/probe-cli/pull/46 we're going towards a direction where we just invoke MK for running a single measurement with a single input, therefore it doesn't matter whether we remove this functionality or not. Thus, I'd not remove it, so that we keep the API stable.
