### ISSUE TITLE
Possible Telegram false positive

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/measurement-kit#1704]
We’ve been notified about a possible Telegram false positive where’s a user can use Telegram via web but Telegram web is blocked according to our app.

I have asked the user to give us more info. I’ll also review the code and see if I can guess how that could happen.

**Comment by bassosimone** [comment]
I have seen the logs. Apprently before v2.0 of the OONI app, still in beta, we did not allow the user to select verbose logs, which makes it harder for me to understand real issues like this. In any case, it seems that the reason why the Telegram test fails for that person is that connection to one of the endpoints fails. There are no further details because of the lack of detailed logs. I am not sure it’s correct to flag the whole test as failed in such case.

**Comment by hellais** [comment]
Do we have a sample measurement that shows this false positive?

**Comment by hellais** [comment]
From looking at the above raw measurement, it seems that:
a. `telegram_web_failure` == `null` -> this means that the blocking reason is not set to `blocked` due to this if statement: https://github.com/measurement-kit/measurement-kit/blob/master/src/libmeasurement_kit/ooni/telegram.cpp#L79
b. The string `Telegram Web` is present in the `<title>` tag of some of the response bodies.

Based on this I suspect the culprit for this is the `extract_html_title` function.

Maybe it's useful to add a unittest that check if it works for the payload of the above measurements.

**Comment by bassosimone** [comment]
> Maybe it's useful to add a unittest that check if it works for the payload of the above measurements.

Yeah, this is a good suggestion. I believe in general we should refactor the code in (1) measure and (2) results processing. This change should facilitate doing what you do in a very scalable way. With this I mean: take all existing measurements and reprocess them with MK logic.

**Comment by bassosimone** [comment]
So, I started to investigate this in master and actually did some small changes to the code in https://github.com/measurement-kit/measurement-kit/pull/1711#issue-239910054 without really understanding the whole story for now. I've not been able to draw any final conclusions yet, and the code in #1711 AFACIT does not change the code logic. Will look into this again tomorrow.

With respect to this comment by @hellais:
> Based on this I suspect the culprit for this is the `extract_html_title` function.

Thanks, this was a good lead. However, after checking, I've noticed that the title is `Telegram Web` in both requests, so I believe this is not the reason of the false positive.

**Comment by bassosimone** [comment]
So, this is the _raw_ report: https://api.ooni.io/files/download/2018-12-14/20181214T152908Z-CU-AS27725-telegram-20181214T152919Z_AS27725_EtDLMUf3zykhNQogEEnmQXUFrsbY3OZKSJBBHDYTwzN1lqiOX7-0.2.0-probe.json

**Comment by bassosimone** [comment]
I believe at this point it's smart to stop and postpone this to v0.9.2 (or v0.10.0). I owe @lorenzoPrimi an usable MK release before end of week, so better to focus on that.

**Comment by bassosimone** [comment]
This issue is deeply linked with #1711. I thought there was a bug, so I refactored the code to make it more consistent with the spec. Actually, the code is okay and the bug disappeared in v0.9.1, while it is still present in v0.8.4. At that point, I already had an open PR. So let's use the PR open to track the bug and let's close this issue, to avoid having two items referring to the same problem.
