### ISSUE TITLE
mkcollector: retry immediately on connect error

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/measurement-kit#1708]
See https://github.com/ooni/sysadmin/issues/266#issuecomment-448555844

We concluded with @darkk that, when we see a timeout when connecting, then most likely we’ve hit a network error.

In terms of CURL, this is probably limited to CURLE_CANNOT_RESOLVE_HOST and CURLE_CANNOT_CONNECT. I am not sure there is a specific need to check for more detailed network errors. (But I am now travelling and from mobile, so I will also make sure I’ll double check this when I will be sitting on a proper chair.)

**Comment by darkk** [comment]
Yes, having `connect()` timeout as the first step is some easy enhancement. It also does not need any _"open new report"_ code as `connect()` timeout clearly states that there is no risk of duplicate measurement as soon as HTTP transaction was not open yet.

**Comment by bassosimone** [comment]
Yes, if we only retry after connect or resolve errors, the logic is quite simple indeed
