### ISSUE TITLE
Error improvements

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/measurement-kit#176]
During the review of #175, @anadahz suggested to further enhance the `common::Error` class to allow to store into the error more context information such as the name of the class that triggered the error, the file name, the line. I think this can be implemented using macros (or inline functions?).

**Comment by hellais** [comment]
I think that error codes should already include all the information necessary to understand what you describe above. If that is not the case then probably the error code is not sufficiently detailed.

This does not mean that you should not implement this, it's an important debugging feature, but it should be possible from just the error string and/or integer to learn exactly WHY the error happened and WHAT triggered it.
