### ISSUE TITLE
Typo in v0.9.6 release description

### ISSUE THREAD

**Issue by ja-pa** [measurement-kit/measurement-kit#1766]
from https://github.com/measurement-kit/measurement-kit/releases/tag/v0.9.6
"This is exactly like **_v0.9.6._** Binary users should use v0.9.4 (and there are no published binaries for v0.9.5 anyway). Source users that happen to use the last release would benefit from this tag, because that means they will use a stable, non buggy release (v0.9.5 introduced a regression)."

@bassosimone  v0.9.6 above should be probably changed to 0.9.4

**Comment by bassosimone** [comment]
Totally! Edited now, thank you!
