### ISSUE TITLE
Test to detect if DNS over HTTPS/TLS is blocked

### ISSUE THREAD

**Issue by anadahz** [measurement-kit/measurement-kit#1838]
This is an issue to create a test to detect if DNS over HTTPS/TLS is blocked.
There maybe a better way to implement this on the engine but it may complicate things.

**Comment by bassosimone** [comment]
Yeah, such a test would be nice. And I guess the engine is a better place where to implement it.

I'm going to close this issue and open an equal issue for the engine.

**Comment by bassosimone** [comment]
- https://github.com/ooni/probe-engine/issues/6

- https://github.com/ooni/probe-engine/issues/5

Thanks for suggesting this feature!

**Comment by anadahz** [comment]
This resource may be helpful during testing of the tests:
https://www.bortzmeyer.org/dns-over-tls-atlas-measures.html
