### ISSUE TITLE
GeoIP script doesn't work 

### ISSUE THREAD

**Issue by ja-pa** [measurement-kit/measurement-kit#1908]
GeoIP script doesn't work. Starting December 30, Maxmind changed the way how it is possible to access their database see https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/

https://github.com/measurement-kit/measurement-kit/blob/master/script/autogen.d/geoip

**Comment by bassosimone** [comment]
You're right. It's still unclear to us the proper way of downloading the new database using an API key and the extent to which we can include this as part of automation. In the meanwhile, maybe what we can do is to adjust the build script to download from https://github.com/ooni/probe-assets/releases/tag/20191226162429. That release contains the latest publicly available version of the MaxMind database.

**Comment by pboothe** [comment]
The build for this repo is currently broken, which transitively is breaking ndt-server builds. For now, I am commenting out measurement-kit in the ndt-server testing process. Please let me know when this is resolved so I can put it back in.

**Comment by bassosimone** [comment]
@pboothe I should have fixed the build in `master` and `v0.10.9`
