### ISSUE TITLE
traceroute: write tests covering socket API failures

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/measurement-kit#194]
Currently traceroute code does not have test cases covering socket functions failure. So, for example, we don't know if the code behaves correctly when `recvmsg()` returns zero. Test cases should be added to the unit test to ensure that strange return values from C functions are correctly handled.

**Comment by bassosimone** [comment]
To start working on this issue:

- list all the C-library (or libevent) functions that are called by the traceroute code

- add stubs for those functions to the `Libs` object, of course if they're not already part of `Libs`

- modify `TracerouteAndroid()` constructor to take an optional `Libs` parameter (using as default value `Libs::global()`)

- modify the implementation to call those functions through the local copy of the `Libs` parameter

**Comment by AntonioLangiu** [comment]
I'm working on this. Instead of using `Libs` I tried to use templates to debug the libevent functions but it is really difficult to do it without rewriting the class, because quite all the methods that we need to debug are private methods of the class!

**Comment by bassosimone** [comment]
We're not going to work on this issue. We'll focus on the Go engine instead.
