### ISSUE TITLE
ios: fix build script wrt jansson and libmaxminddb

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/measurement-kit#208]
The iOS build script should explicitly tell configure to use the builtin jansson and libmaxminddb, to avoid using system-wide libraries for another architecture, if they are installed.

This should mirror [what is already done for boost etc](https://github.com/measurement-kit/measurement-kit/blob/master/mobile/ios/scripts/build_arch.sh#L35). To see what flags are defined, I suggest to read the output of `./configure`.

**Comment by AntonioLangiu** [comment]
See [this](https://github.com/measurement-kit/measurement-kit/pull/215) pull request.
