### ISSUE TITLE
ios: build should not continue after first failure

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/measurement-kit#209]
We use `sh -e` extensively but apprently this is not enough. See for example [this travis build](https://travis-ci.org/measurement-kit/measurement-kit-app-ios/builds/90504361#L197) where compilation should stop after the first configure error and instead continues.

**Comment by AntonioLangiu** [comment]
I was right now not able to fix this. The `set -e`instruction doesn't work outside the sub-shell. 

To test it I [put](https://github.com/measurement-kit/measurement-kit/blob/2953a1004baabd683f5e5408d1620f3a622c72b8/mobile/ios/scripts/build_arch.sh#L30) `set -e` in the subshell and I [explicity generated an error](https://github.com/measurement-kit/measurement-kit/blob/2953a1004baabd683f5e5408d1620f3a622c72b8/mobile/ios/scripts/build_arch.sh#L32), but the compilation in Travis-ci seems [not stop](https://travis-ci.org/measurement-kit/measurement-kit-app-ios/builds/91607168) after the first error. Have you some other ideas? @bassosimone

**Comment by AntonioLangiu** [comment]
Maybe a solution can be to check the returned value of the [child-script](https://travis-ci.org/measurement-kit/measurement-kit-app-ios/builds/91607168) (build_arch) and exit from the parent-script if the returned value is 1.

**Comment by bassosimone** [comment]
Moving to a future release because that's not a show stopped. In any case, [I encountered and fixed this issue when I was working on mpkm-ng](https://github.com/bassosimone/mkpm-ng/blob/master/script/mkpm-install-plumbing#L107).

**Comment by AntonioLangiu** [comment]
I think this PR should be closed. We are actually not cross-building inside travis and this problem doesn't occour when cross-building locally! @bassosimone you will have the honor!

**Comment by bassosimone** [comment]
>  @bassosimone you will have the honor!

LOL
