### ISSUE TITLE
ios: make build scripts independent of directory

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/measurement-kit#210]
See how I did the same [for Android's build.sh](https://github.com/measurement-kit/measurement-kit/blob/master/mobile/android/scripts/build.sh#L3)

**Comment by AntonioLangiu** [comment]
It should be fixed with [this](https://github.com/measurement-kit/measurement-kit/commit/ebb4131e12784f526b5388c6c0bd46dd33056dfd) commit.

**Comment by AntonioLangiu** [comment]
This works now. See [this PR](https://github.com/measurement-kit/measurement-kit/pull/212), and expecially this commits:

* [Add instructions to set the working folder for the scripts
](https://github.com/measurement-kit/measurement-kit/commit/ebb4131e12784f526b5388c6c0bd46dd33056dfd)

* [Change $0 to BASH_SOURCE[0]](https://github.com/measurement-kit/measurement-kit/commit/08f3e89bb1723de56cfa07bc15a7b5e60d042554)

**Comment by bassosimone** [comment]
@AntonioLangiu says that this is instrumental to do #264 hence I've moved this back to the milestone of release 0.1.0.

**Comment by bassosimone** [comment]
With #212 merged, I guess we can close this now, right, @AntonioLangiu?

**Comment by AntonioLangiu** [comment]
yess!
