### ISSUE TITLE
build system: normalize --with names

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/measurement-kit#211]
IMO if the project is named boost, the flag should be `--with-boost`. If the project is named libevent, the flag should be `--with-libevent`. That is, `--with-` followed by the name of the project on github. This makes it super easy for someone to guess the name of the dependency. Currently, I guess the flags for `yaml-cpp` and `boost` are wrong, because they prefix `lib` to the name.

**Comment by AntonioLangiu** [comment]
The [included libraries](https://github.com/measurement-kit/measurement-kit/tree/master/src/ext) are:
* boost
* jansson
* libevent
* libmaxminddb 
* yaml-cpp

I think (watching the projects source) that the name of the project should be: 
* [boost](http://www.boost.org/users/download/)
* [jansson](https://github.com/akheron/jansson)
* [libevent](http://libevent.org/)
* [libmaxminddb](https://github.com/maxmind/libmaxminddb)
* [yaml-cpp](https://github.com/jbeder/yaml-cpp)

Actually we are using in the [build script](https://github.com/measurement-kit/measurement-kit/blob/issue-208/mobile/ios/scripts/build_arch.sh) this flags: 
* --with-libboost
* --with-jansson
* --with-libevent
* --with-libmaxminddb
* --with-libyaml-cpp

So we should change the flag `libboost` to `boost`and `libyaml-cpp` to `yaml-cpp`as you said.

**Comment by AntonioLangiu** [comment]
I made it in [this](https://github.com/measurement-kit/measurement-kit/tree/issue-211) branch!
