### ISSUE TITLE
dns: review code to generate reverse addresses for PTR queries

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/measurement-kit#222]
@hellais, during the review process of #175, you stated that you wanted to carefully review [the code to generate reverse addresses for PTR queries](https://github.com/measurement-kit/measurement-kit/blob/master/src/common/utils.cpp#L272) before we go stable. That pull request has now been merged to prepare our first alpha release. This issue serves as a reminder to review that block of code.

**Comment by hellais** [comment]
This looks good to me.
