### ISSUE TITLE
Find a way to generate code coverage reports

### ISSUE THREAD

**Issue by hellais** [measurement-kit/measurement-kit#23]
It would be nice to have reports on what is the current code coverage of libight. The unittesting framework we chose (Catch) does not seem to support this natively, but it looks like it is something that can be done with `clang --coverage`.

Doing a little bit of research I came up with these links that may be useful:

* http://stackoverflow.com/questions/19881928/code-coverage-in-clang
* http://clang-developers.42468.n3.nabble.com/Code-coverage-on-clang-td4033066.html

Alternatively expcov also seems promising:

* http://www.expcov.com/

**Comment by bassosimone** [comment]
Forget about that branch, @AntonioLangiu. First thing I'd do is to investigate how the [neovim project](https://github.com/neovim/neovim) does to have code coverage using coveralls.

**Comment by bassosimone** [comment]
Since this is already done and submitted as a pull request and we have still time before the stable release, I've changed the milestone to 0.1.0 and will merge it soon.
