### ISSUE TITLE
Stop installing Boost header

### ISSUE THREAD

**Issue by DavideAllavena** [measurement-kit/measurement-kit#236]
Maybe through Makefile.am?

**Comment by bassosimone** [comment]
@DavideAllavena, if not Makefile.am, one of the include.am files that Makefile.am includes. Anyway, I was thinking that the correct issue is not just to avoid installing boost headers but rather to avoid installing any third-party header. To this end, we may also want to consider changing the install scripts for android and ios to invoke `make` in a way in which only measurement-kit headers are installed.
