### ISSUE TITLE
stream.hpp can possibly throw an error

### ISSUE THREAD

**Issue by DavideAllavena** [measurement-kit/measurement-kit#240]
Taking .as_value() in src/http/stream.hpp causes an exception to be thrown if the connect() function failed in some way.

We need to deal with with when we deal with all the errors that can happen in the implementation of HTTP.

Does this need to be fixed soon @bassosimone?

**Comment by bassosimone** [comment]
Well, @DavideAllavena, I think this is part of the larger task dealing with refining and improving the implementation for reliability, which is something to do after 0.1.0 is out.

**Comment by bassosimone** [comment]
We can close this issue. `src/http/stream.hpp` now sleeps with the fishes, hence this issue is not relevant anymore :-).
