### ISSUE TITLE
Run BaseTest::run() in the current thread with a dedicated poller

### ISSUE THREAD

**Issue by DavideAllavena** [measurement-kit/measurement-kit#246]

**Comment by bassosimone** [comment]
Or, do we prefer to always run measurement-kit tests in a background thread?

**Comment by bassosimone** [comment]
To clarify what I mean here, see the code and specifically the XXX comment: https://github.com/measurement-kit/measurement-kit/blob/master/src/ooni/base_test.cpp#L20

**Comment by bassosimone** [comment]
Closings because #949 addressed this issue.
