### ISSUE TITLE
Avoid including external header when building for iOS

### ISSUE THREAD

**Issue by DavideAllavena** [measurement-kit/measurement-kit#247]
In order to avoid the installation of external header the build script for iOS should replace `make install` with:

```
make install-data-am
make install-exec
```

See also the Android script.

**Comment by bassosimone** [comment]
Actually, the proper way of doing that is even more complex. See [the Android script for more details](https://github.com/measurement-kit/measurement-kit/blob/master/mobile/android/scripts/build_target.sh#L90).

**Comment by bassosimone** [comment]
Since @AntonioLangiu is taking care of this in #212, I will assign this issue to him.

**Comment by AntonioLangiu** [comment]
Already [done](https://github.com/measurement-kit/measurement-kit/commit/9c980280be6eb72701dd558b12c7511faf2b7b20#diff-01d3aeeba0bf1359bd3d77980bc04b77R51) in this commit!

**Comment by bassosimone** [comment]
I guess also this one can be closed, since #212 was merged, right, @AntonioLangiu?

**Comment by AntonioLangiu** [comment]
yess!
