### ISSUE TITLE
Release binaries using CocoaPods

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/measurement-kit#264]
We should build v0.1.0-beta.1 for cocoapods and upload the resulting binaries in the cocoapod "store" such that it's possible to download them when building the iOS application.

**Comment by AntonioLangiu** [comment]
I will finish first #210 because this depends on it.

**Comment by bassosimone** [comment]
@AntonioLangiu I suggest to use the same approach that I've used for Android. That is, use the output of `git describe --tags` to annotate the version number. This way, we can produce builds of releases (especially alpha and beta ones) that are one-two commits after the "formal" release point. And those two commits can be precisely the ones that fix trivial bugs that one typically discovers around release.

**Comment by AntonioLangiu** [comment]
Before pushing the pod with `pod trunk` I would like to fix this warning produced by `pod lint`(a tool to validate Podspec files): 

    ** BUILD SUCCEEDED **

     -> measurement_kit (0.0.1)
        - WARN  | source: Git sources should specify a tag.

     Analyzed 1 podspec.

    [!] The spec did not pass validation, due to 1 warning (but you can use `--allow-warnings` 
    to ignore it) and All results apply only to public specs, but you can use `--private` to ignore
    them if linting the specification for a private pod..

The [official documentation](https://guides.cocoapods.org/making/making-a-cocoapod.html#release) says that "Once you have a release ready you'll need to make the corresponding tag"

@bassosimone what do you think about it?

**Comment by bassosimone** [comment]
There are already tagged releases. I am about to tag 0.1.0-beta.4. I think you should use that tag in the cocoapod specification file. Also, remember to update the version number inside that file.

**Comment by AntonioLangiu** [comment]
Ok! I found out a solution! :+1:

**Comment by AntonioLangiu** [comment]
I pushed the first [pod to cocoapod](https://raw.githubusercontent.com/CocoaPods/Specs/02bb5d11b30c8f44187051907ac7d5e05a6a6b67/Specs/measurement_kit/0.1.0-beta.3/measurement_kit.podspec.json)!!

It seems working with the Xcode project, but before the first release you need to specify the version that you want to download! This problem should be fixed when we make the first release tagged 0.1.0 

I paste here the error:

    [!] There are only pre-release versions available satisfying the following requirements:

        'measurement_kit', '>= 0'

        You should explicitly specify the version in order to install a pre-release version


Actually we are just sending [this file](https://raw.githubusercontent.com/CocoaPods/Specs/02bb5d11b30c8f44187051907ac7d5e05a6a6b67/Specs/measurement_kit/0.1.0-beta.3/measurement_kit.podspec.json) that download the sources and build it. 
I'm working to have two choises, like [ESLocale did for this repository](http://cocoapods.org/?q=ESLocal), so the user can download the compiled version or the "source" version.

**Comment by AntonioLangiu** [comment]
[Here](https://github.com/CocoaPods/CocoaPods/issues/2731) there is a huge discussion if it is better the compiled version or the 'source code' version. I think that both have advantages and disadvantages.

I write here the disadvantages:

 - With the compiled version the developer can't see (or maybe change) the code before installing and he has to trust the binary that cocoapod downloads; when there is a new architecture (it is not so common for iOS) we have to push another binary to support it, and so we have to maintain this system. 
 - With the source code version the user have to compile it and it can take a long time (depends on the machine); 

I think the best solution is to send the two version and let the developer choose which one he prefers.

**Comment by bassosimone** [comment]
How do I test this?

**Comment by bassosimone** [comment]
Regarding the sources vs. binary choice: at the moment what is important is to have the binaries. The sources-based solution could be implemented later, since it's not priority at the moment.

**Comment by bassosimone** [comment]
Shifted in time, because this is not *required* to make a release.

**Comment by lorenzoPrimi** [comment]
@bassosimone I guess we can close this

**Comment by bassosimone** [comment]
Yes, thank you!
