### ISSUE TITLE
Test v0.1.0-beta.1 with the iOS application

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/measurement-kit#265]
In the context of this task we should download the binaries built with cocoapods and update the iOS application to work with the API of v0.1.0-beta.1. Then we should test the application.

**Comment by AntonioLangiu** [comment]
I will do it while working on #269.

**Comment by bassosimone** [comment]
That would be great, thank you! :+1:

**Comment by AntonioLangiu** [comment]
I will finish first #210 because this depends on it.

**Comment by AntonioLangiu** [comment]
I'm working on this in [this PR](https://github.com/measurement-kit/measurement-kit-app-ios/pull/26)

**Comment by bassosimone** [comment]
Pull request measurement-kit/measurement-kit-app-ios#26 can be used to test this. I will do that this afternoon using both the emulator and device. As discussed with @AntonioLangiu, it is not priority to merge immediately such pull request (which probably needs some more cleanups). We only need this pull request as a base to ensure that measurement-kit 0.1.0 will be compatible with the app.

**Comment by bassosimone** [comment]
Assigned to myself since now it's my task to double check that this works.

**Comment by bassosimone** [comment]
Ok. I've tested this on emulator and device and pushed couple of fixes. The measurement-kit/measurement-kit-app-ios#26 pull request needs more love before it can be closed. But, this testing I did was enough to declare this issue closed.
