### ISSUE TITLE
Write tutorial for iOS and Android and C++

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/measurement-kit#269]
This should only cover using MeasurementKit at high level, i.e. at the level of running OONI tests and for now I'd not include low level stuff into the tutorial.

**Comment by AntonioLangiu** [comment]
I can write it for iOS.

**Comment by bassosimone** [comment]
Okay!

**Comment by bassosimone** [comment]
@AntonioLangiu BTW, I have found this tutorial of libevent by Nick Mathewson to be a good tutorial, maybe you can try to use it as blueprint? http://www.wangafu.net/~nickm/libevent-book/

**Comment by bassosimone** [comment]
Written for Android and Unix. Still need to write the one for iOS.

**Comment by bassosimone** [comment]
Also written for iOS. Pull request #304 is now being reviewed by @AntonioLangiu.
