### ISSUE TITLE
Add index in readme.md

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/measurement-kit#271]
I'd add such index just before the section called "How to clone the repository" because the initial set of statements is general purpose and informational. Basically I'd conclude that initial set of statement in a paper-like way stating that "the remainder is organized as follows" and then I'll add the index.

**Comment by AntonioLangiu** [comment]
I'm using [this](https://github.com/tiimgreen/github-cheat-sheet/blob/master/README.md) as a template.

**Comment by bassosimone** [comment]
Alright, thanks!
