### ISSUE TITLE
Make sure we do not throw std::runtime_error

### ISSUE THREAD

**Issue by AntonioLangiu** [measurement-kit/measurement-kit#276]
Since we have introduced [specific errors for http problems](https://github.com/measurement-kit/measurement-kit/blob/master/include/measurement_kit/http/error.hpp), in the implementation of  [request_serializer](https://github.com/measurement-kit/measurement-kit/blob/master/src/http/request_serializer.cpp#L31)  we should use those errors instead of `std::runtime_error`

**Comment by AntonioLangiu** [comment]
This is also happening [here](https://github.com/measurement-kit/measurement-kit/blob/master/src/net/transport.cpp#L58) in the net/transport.ccp file.

**Comment by AntonioLangiu** [comment]
Update title since the fix is not just in the request class!

**Comment by AntonioLangiu** [comment]
@bassosimone I changed the std::runtime_error to the error defined in the [http error header](https://github.com/measurement-kit/measurement-kit/compare/issue-276#diff-1510b5e76273aab6d6182bcebe25ae84L28).

Should I introduce new errors to rapresent [this](https://github.com/measurement-kit/measurement-kit/compare/issue-276#diff-1510b5e76273aab6d6182bcebe25ae84L31) or [this](https://github.com/measurement-kit/measurement-kit/compare/issue-276#diff-1510b5e76273aab6d6182bcebe25ae84L34) error?

**Comment by bassosimone** [comment]
Yes. More specifically, we have three new errors here:

- the URL parser error (which is different from the HTTP parser error)

- the missing URL schema error

- the missing URL host error
