### ISSUE TITLE
Change the name of the dumb class

### ISSUE THREAD

**Issue by AntonioLangiu** [measurement-kit/measurement-kit#279]
The [`dumb` class](https://github.com/measurement-kit/measurement-kit/blob/master/src/net/dumb.hpp#L20) contained in src/net, it is a base class for the [`connection`](https://github.com/measurement-kit/measurement-kit/blob/master/src/net/connection.hpp#L37)and the [`socks5`](https://github.com/measurement-kit/measurement-kit/blob/master/src/net/socks5.hpp#L21) class. So it should have a more fitting name for his role (like `emitter`);

What do you think @bassosimone?

**Comment by bassosimone** [comment]
Yes, I think `Emitter` is a good name for that role, while `Dumb` is a terrible name :).

**Comment by AntonioLangiu** [comment]
I close it because we already merged the PR 285.
