### ISSUE TITLE
The class connection should be not copyable and not movable 

### ISSUE THREAD

**Issue by AntonioLangiu** [measurement-kit/measurement-kit#280]
As wrote [here](https://github.com/measurement-kit/measurement-kit/blob/master/src/net/connection.cpp#L99) the class `connection` should be not copyable and not movable but I didn't' find an assignment in the class to do this (neither in the base class it extends).

**Comment by bassosimone** [comment]
Good catch! I suggest to publicly inherit NonCopyable and NonMovable in Connection rather than in subclasses, since this is the most accurate thing (Dumb for example is movable and one may actually want to move it for a good reason).
