### ISSUE TITLE
Teach cocoapod to install libresolv

### ISSUE THREAD

**Issue by AntonioLangiu** [measurement-kit/measurement-kit#305]
In the iOS App to update the resolver [we need libresolv.tbd](https://github.com/measurement-kit/measurement-kit/pull/304/files#diff-f290cac701fa72fa288bed0f2150af2aR173). We can use cocoapod to install it automatically.

**Comment by AntonioLangiu** [comment]
I think this is not a problem of measurement-kit! Closing!

**Comment by bassosimone** [comment]
Sure but please also add a corresponding issue in the proper repository!

**Comment by bassosimone** [comment]
(And then close again this one when done!)

**Comment by AntonioLangiu** [comment]
I think this issue should not be here. I'm moving it to Measurement-kit-app-ios
