### ISSUE TITLE
Add code to initialize resolver to MK iOS framework

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/measurement-kit#306]
While writing the iOS tutorial I realized it would be great to factor the code to initialize the resolver using the device DNS inside a function, because that's not three lines of code.

<strike>By the way, this is not just initialization. The system DNS should be queried before every test, because mobile devices move. Hence we need to use the freshest DNS available not a stale one.</strike> [This second sentence is now an issue of its own, namely #331]

**Comment by lorenzoPrimi** [comment]
Are we talking iOS or Android?

**Comment by bassosimone** [comment]
iOS

**Comment by AntonioLangiu** [comment]
Since we are able to pass settings to the DNS from every test I think that this issue is not valid, right @bassosimone?

**Comment by AntonioLangiu** [comment]
Sorry, I misundestand the meaning of this PR, that is actually to write objective-C code that take and set the dns to run the tests. I'm moving this issue to the [correct repository](https://github.com/measurement-kit/measurement-kit-ios), where we will put all the objective-C code that interacts with Measurement-Kit.
