### ISSUE TITLE
Fix memory leak in delayed_call test

### ISSUE THREAD

**Issue by AntonioLangiu** [measurement-kit/measurement-kit#320]
Sine we are usign valgrind to run regress test we have a [memory leak problem (?) with the delayed_call test](https://travis-ci.org/measurement-kit/measurement-kit/jobs/97945929#L1185)

This problem should not be related to the code but to the fact that valgrind changes somehow the way the code is executed and so the test fails.

**Comment by bassosimone** [comment]
Well, this was not fixed but the test was removed along with `DelayedCall`. We can thus close this issue.
