### ISSUE TITLE
Fix memory leak in test/http/stream

### ISSUE THREAD

**Issue by AntonioLangiu** [measurement-kit/measurement-kit#321]
This is the output of valgrind running test/http/stream

    ==1532==
    ==1532== HEAP SUMMARY:
    ==1532==     in use at exit: 1,262 bytes in 27 blocks
    ==1532==   total heap usage: 922 allocs, 895 frees, 83,234 bytes allocated
    ==1532==
    ==1532== 1,262 (96 direct, 1,166 indirect) bytes in 1 blocks are definitely lost in loss record 23 of 23
    ==1532==    at 0x4C2B0E0: operator new(unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-    amd64-linux.so)
    ==1532==    by 0x41137D: ____C_A_T_C_H____T_E_S_T____60() (stream.cpp:69)
    ==1532==    by 0x433FD7: invoke (catch.hpp:6715)
    ==1532==    by 0x433FD7: invokeActiveTestCase (catch.hpp:5412)
    ==1532==    by 0x433FD7: runCurrentTest (catch.hpp:5384)
    ==1532==    by 0x433FD7: runTest (catch.hpp:5223)
    ==1532==    by 0x433FD7: Catch::Runner::runTests() (catch.hpp:5543)
    ==1532==    by 0x434E05: Catch::Session::run() (catch.hpp:5670)
    ==1532==    by 0x406183: run (catch.hpp:5650)
    ==1532==    by 0x406183: main (catch.hpp:9234)
    ==1532==
    ==1532== LEAK SUMMARY:
    ==1532==    definitely lost: 96 bytes in 1 blocks
    ==1532==    indirectly lost: 1,166 bytes in 26 blocks
    ==1532==      possibly lost: 0 bytes in 0 blocks
    ==1532==    still reachable: 0 bytes in 0 blocks
    ==1532==         suppressed: 0 bytes in 0 blocks
    ==1532==
    ==1532== For counts of detected and suppressed errors, rerun with: -v
    ==1532== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)

**Comment by bassosimone** [comment]
I've merged a pull request containing a fix for this. Thank you for spotting this!
