### ISSUE TITLE
osx on travis: test/dns/query fails 

### ISSUE THREAD

**Issue by AntonioLangiu** [measurement-kit/measurement-kit#324]
The reverse dns lookup fails while building with travis on a osx machine. Here is an [example of the build](https://travis-ci.org/measurement-kit/measurement-kit/jobs/99581463#L533)

**Comment by bassosimone** [comment]
Since this does not happen when running tests locally on OSX systems, I'm inclined to say that this depends on the specifics of travis deployment. First thing that comes to my mind, have you tried to run `brew update` before the `script` phase of travis?

**Comment by AntonioLangiu** [comment]
No, I will try :+1:

**Comment by AntonioLangiu** [comment]
I'm trying with `brew update` and `brew upgrade` before the script. It seems not working right now.

**Comment by bassosimone** [comment]
This has been fixed @AntonioLangiu in #456 (see also [the relevant travis-ci build(https://travis-ci.org/measurement-kit/measurement-kit/builds/122485739)).
