### ISSUE TITLE
Create build script for special cases (iOS, Android)

### ISSUE THREAD

**Issue by AntonioLangiu** [measurement-kit/measurement-kit#325]
It can be useful to have a directory containing different build script for all the special cases like iOS build or Android, but also normal build for Linux or OS-X. This is useful when we need to call build script from Travis in a conditional case, like [here](https://github.com/measurement-kit/measurement-kit/blob/issue-322/.travis.yml#L26).

I have temporarily found a solution for the iOS build, but I don't' like it because we stop the Travis build script with `exit 0`;

**Comment by bassosimone** [comment]
So, the problem you are trying to solve is that you want to launch a full ios build from travis, correct?

Could the script phase become something like the following?

```
- autoreconf -i
- if [ "${BUILD_TYPE}" = "ios" ]; then
     ./mobile/ios/build.sh;
  elif [ "${BUILD_TYPE}" = "android" ]; then
    ./mobile/android/build.sh;
  else
    ./configure && make V=0 && make check-am V=0;
fi
```

**Comment by AntonioLangiu** [comment]
Ok thank you, I used your solution. I'm just using some bash variables in the install section (before the script) to avoid having a big if condition, like is [here.](https://github.com/measurement-kit/measurement-kit/blob/issue-322/.travis.yml#L22)
