### ISSUE TITLE
Add code to specify the DNS server to be used by a test

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/measurement-kit#331]
Since we target mobile applications, we cannot just read the DNS server from the device when the app starts and then rely on that. Because the device can be moved into other networks. Hence, we should use, when we initiate a test, the most recently known DNS server. To this end, there should be a method of the test factory class (e.g. `ooni::DnsInjectionTest`) that allows one to specify the DNS server to be used, specified as a string.

**Comment by bassosimone** [comment]
@AntonioLangiu can we close this issue?

**Comment by AntonioLangiu** [comment]
Yes, we can close this issue 👍
