### ISSUE TITLE
dns_injection: no need to store callback inside object

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/measurement-kit#337]
The callback passed to dns_injection::main() could instead be stored inside the lambda passed to `query()`. After this change, make sure with Valgrind that the memory allocated by the test is correctly released (I recall that I applied this change to plug a memory leak, back when it was not totally clear to me that such leaks where called by circular references).

**Comment by AntonioLangiu** [comment]
I think this has been solved in [this](https://github.com/measurement-kit/measurement-kit/commit/91021de0a80fdded7e6f806995feb56db24e5219) commit!
