### ISSUE TITLE
tcp_connect.hpp: improve usage of lambda closures

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/measurement-kit#345]
We don't need to save the callback as an object attribute. It should suffice to store it inside the closure of the other lambda. Remember to check with Valgrind this does not cause memory errors.

**Comment by AntonioLangiu** [comment]
I think we can close this PR because it has been done [here](https://github.com/measurement-kit/measurement-kit/commit/1da364163f63f9a3ece7c7e593f9c3af8f0f16e7#diff-dde24650d0ceec00219498077398bb3cR41).

**Comment by bassosimone** [comment]
Yes, thanks!
