### ISSUE TITLE
Renames pending in src/ooni/

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/measurement-kit#347]
The files should be named `foo_impl.hpp` for each `foo` test. Likewise, the classes should be named `FooImpl` for each `foo` test. This should clarify those files / classes are the implementation of tests rather than the interface to run tests (which is instead in `include/measurement_kit/ooni.hpp`).

**Comment by DavideAllavena** [comment]
I start working on this issue

**Comment by bassosimone** [comment]
Added bikeshedding because there was agreement over this :-)
