### ISSUE TITLE
Make sure error numbers are consistent across modules

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/measurement-kit#348]
There should be no duplicates in different modules. Maybe we should also consider adding a "namespace" for error numbers (a string?) such that each module is free to declare its own error numbers? Is it possible to use type information to distinguish between errors instead? (The latter would be epic meaning that we can get rid of assigning a number to each error to allow for comparison).

**Comment by DavideAllavena** [comment]
First fix: started a branch with the same name of the issue. Traceroute error numbers are moved from 2000 to 4000 to be consistent. Next I'll check the rest of the issue.

**Comment by bassosimone** [comment]
Perfect! I've opened #350 to merge this change. I'd say we can keep this issue open to discuss whether there is need to <strike>bikeshed</strike> find a less error-prone solution to distinguish errors. Thanks!
