### ISSUE TITLE
define procedure to update all version numbers throughout the code

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/measurement-kit#359]
I've just noticed `<measurement_kit/common/version.hpp>` is out of date. Perhaps there are also other outdated version numbers around. Should track all of them and find a way to fix them all at once.

**Comment by DavideAllavena** [comment]
I can check this.

**Comment by bassosimone** [comment]
Ok, thank you! I guess there are some places with out-of-date versions. I run a grep to find them on release but I missed them. Probably they are still at 0.1.0.
