### ISSUE TITLE
OSX on travis failure

### ISSUE THREAD

**Issue by AntonioLangiu** [measurement-kit/measurement-kit#448]
The build on the OSX machine on travis fails due to the test [`test/net/connect`](https://travis-ci.org/measurement-kit/measurement-kit/jobs/120867977#L4721).

The problem is that it expects a `NetworkError` but it receives a `TimeoutError`. I was able yesterday to reproduce this problem locally, but it happens just in some Network conditions. (For example now the test pass)

@bassosimone and @DavideAllavena do you think that we should check for both? Is it normal that when you try to make a connection to a closed port of a server you have a timeout problem?

**Comment by bassosimone** [comment]
Yes, this seems reasonable. I did some testing as well and managed to reproduce the issue here for me in a couple of cases, under OSX. Please, go ahead!

**Comment by AntonioLangiu** [comment]
So, I was able to reproduce the error setting a rule to the firewall to block all the icmp packets. 
So the problem seems that the travis osx machine blocks icmp (or maybe just the type 3: Destination Unreachable, that is what we need in this case), so the test receive a `TimeoutError` instead of a `NetworkError`. 
If you want to reproduce the test on your machine you can try with ubuntu and iptables, or like I did with mac and pfctl. Try to add this rule to your `/etc/pf.conf`:

    block in log proto icmp all

and then reload the pfctl configuration with:

    pfctl -Fa -f /etc/pf.conf

You should get the same error reported on travis!

**Comment by AntonioLangiu** [comment]
#456 fixed the problem, as you can see in [this travis build](https://travis-ci.org/measurement-kit/measurement-kit/builds/121883739)

**Comment by bassosimone** [comment]
Thank you for investigating this issue! I think the issue itself could now be closed and the pull request deal with once the requested changes have been applied!
