### ISSUE TITLE
a unit test in test/http/stream is not executing

### ISSUE THREAD

**Issue by AntonioLangiu** [measurement-kit/measurement-kit#453]
[This test](https://github.com/measurement-kit/measurement-kit/blob/master/test/http/stream.cpp#L94) is not executing on travis, because tor is not running!

**Comment by bassosimone** [comment]
Thank you for investigating this! To understand, shouldn't the error handler at least be called if the connection to Tor fails? (That is [from line 105 onwars](https://github.com/measurement-kit/measurement-kit/blob/master/test/http/stream.cpp#L105)))

**Comment by AntonioLangiu** [comment]
Closing this because we will solve this problem with #458
