### ISSUE TITLE
Migrate Poller * and Logger * to Var<Poller> and Var<Logger>

### ISSUE THREAD

**Issue by AntonioLangiu** [measurement-kit/measurement-kit#468]
As spotted by @bassosimone, in [this PR](https://github.com/measurement-kit/measurement-kit/pull/452) we should pass to the test a Var<Poller> and a Var<Logger> instead of raw pointers.

**Comment by bassosimone** [comment]
Assigned to 0.3.0 because it's time we start shifting things to the future and concentrate on finishing this release, or we will delay it too much.

**Comment by bassosimone** [comment]
I did this
