### ISSUE TITLE
Add support for geoip

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/measurement-kit#51]
We should add support for geoip, so that we can hide the IP address of clients in certain cases.

**Comment by bassosimone** [comment]
I've seen that Tor includes [code to manage GeoIP](https://gitweb.torproject.org/tor.git/tree/src/or/geoip.h) but it seems that it contains some Tor specific stuffs. For this reason, I think we should instead just integrate MaxMind's code.

In particular, I think we should integrate [libmaxminddb](https://github.com/maxmind/libmaxminddb) which is used by GepIP2 databases. Judging from [its tests suite](https://github.com/maxmind/libmaxminddb/tree/master/t), the functions to which we are most interested are `MMDB_open()` and `MMDB_lookup_sockaddr()`. The latter returns a `MMDB_lookup_result_s` that, if its `found_entry` field is true, can be queried using `MMDB_vget_value()`.

**Comment by bassosimone** [comment]
Hmm, on the other hand, since we need to integrate Tor which in turn ships with geoip files, it's probably worth a look whether we could use Tor code to fullfill this task.

**Comment by hellais** [comment]
The tor code for geoip will for sure not be able to fulfil all our requirements. For example tor does not ship with the maxmind ASN database that we need.

Since the code is not that much, and it's mainly just a matter of integrating libgeoip, we should go for that route and have our own.

**Comment by bassosimone** [comment]
Ok!

**Comment by bassosimone** [comment]
This has now been merged into master!
