### ISSUE TITLE
Http Invalid Request Line Timeout problem

### ISSUE THREAD

**Issue by AntonioLangiu** [measurement-kit/measurement-kit#556]
When [setting a timeout](https://github.com/measurement-kit/measurement-kit/blob/master/test/ooni/http_invalid_request_line_test.cpp#L70) really low (like 0.0001) for the dns resolution or the tcp connect the test never calls the final callback!

**Comment by AntonioLangiu** [comment]
This issue has been fixed with the new async implementation!

**Comment by bassosimone** [comment]
I'd say "solved" for small values of "solved". I actually added one second delay to avoid the race condition. A better solution is implemented in #543 and could be backported from there.

**Comment by bassosimone** [comment]
In any case, it's true -- as you say -- that the problem indicated here is solved :-)
