### ISSUE TITLE
example/mlabns crashes because of missing ca_bundle_path

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/measurement-kit#566]
So, @AntonioLangiu discovered that example/mlabns is now crashing and debugging it we discovered that the problem is that a default `ca_bundle_path` is missing.

I've opened #564 to start mitigating the problem by warning and throwing a more meaningful error, but more work must be done to definitely close this issue.

As the `XXX` comment in the original code says, we could try harder to find the proper location for the certificate bundle on Linux and MacOS. I think this would be reasonable, provided that we `stat()` to ensure the file exists. Otherwise we could fix this just by setting a specific location in the mlabns example.

In any case, we should modify mlabns code to receive a setting.

@hellais Do you think it would make sense to search for certificate bundles in known paths? Or do we want to ship a bundle specific of MK?

**Comment by AntonioLangiu** [comment]
As a suggestion I propose the solution used in the cURL library, where the [configure script searchs](https://github.com/curl/curl/blob/master/acinclude.m4#L2560) for a default installation of ca_bundle, or you can give it as parameter ([--with-ca-bundle=FILE](https://github.com/curl/curl/blob/master/acinclude.m4#L2577))

**Comment by bassosimone** [comment]
Yes, that seems to be a very good approach! Let's go for it!

**Comment by bassosimone** [comment]
Definitely fixed in #590
