### ISSUE TITLE
Repair currently broken Android build

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/measurement-kit#609]
- [x] make sure we can create toolchains also with NDKs newer than `r10e`
- [x] create `./build/android/dependency` script similar to the iOS one
- [x] tweak build to download precompiled binaries of dependencies as we do for iOS

**Comment by bassosimone** [comment]
Issues identified in #607.

**Comment by AntonioLangiu** [comment]
Start working on this in PR #642 and #643

**Comment by bassosimone** [comment]
Everything now done!
