### ISSUE TITLE
iOS bitcode

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/measurement-kit#658]
I've done some research trying to understand what it means that now on iOS applications are compiled to bitcode. The first question I had in mind is how it was possible that LLVM bitcode could represent code compiled by compilers with different ABIs (32 and 64 bits). After a not-so-short research, it turns out that actually there are two bitcodes, one for iOS 32 bit ABI and another for 64 bit.

I am leaving this issue here because I assume that in the future we may be interested to further understand how to compile using bitcode. Even though, for what I have read, I am against using it.

Relevant links:
- https://code.google.com/p/analytics-issues/issues/detail?id=671
- https://github.com/card-io/card.io-iOS-SDK/issues/119
- https://forums.developer.apple.com/message/7038#7038
- https://github.com/google/gcm/issues/91
- https://medium.com/@FredericJacobs/why-i-m-not-enabling-bitcode-f35cd8fbfcc5#.8ku9pptq7

**Comment by bassosimone** [comment]
cc: @lorenzoPrimi

**Comment by lorenzoPrimi** [comment]
At the moment I'm not using bitcode in my other apps, it's not required.
In the future I might reconsider it.

**Comment by bassosimone** [comment]
Let's close this, for now. Long time has passed and we're fine with normally compiling apps.

**Comment by ThePatient** [comment]
Wasn't sure if I should open a new issue or comment on this one since it is closed, but I am building for iOS and I'd like to enable bitcode.

So far I've been able to build geoip, libevent, and libressl with the `-fembed-bitcode` flag set for `CFLAGS` and `CXXFLAGS` (by changing the value in `build/ios/cross` for the iphoneos platform). 

I haven't been able to use the same technique for building mk though. When I set fembed-bitcode for only `CXXFLAGS` the build succeeds, but when I try to export a project with the framework included I get an error stating `http_parser.o` does not contain bitcode. If I add fembed-bitcode to the `CFLAGS` when building mk I get an SSL error near the end of the armv7 `./build/dependency`: 

```
checking for SSL_new in -lssl... no
checking whether OpenSSL is older than 1.0.0... Skip the test because we are cross-compiling
configure: WARNING: Failed to find dependency: openssl
    - to install on Debian: sudo apt-get install libssl-dev
    - to install on OSX: brew install openssl
    - to compile from sources: ./build/dependency libressl
configure: error: Please, install openssl and run configure again
```

I have openssl installed as well as trying the compile from sources option but nothing seems to be working.

Any ideas?

**Comment by bassosimone** [comment]
> Wasn't sure if I should open a new issue or comment on this one since it is closed

Reopened the issue!

> Any ideas?

I think it would help to see the output of `config.log` (specifically, it would help if you could trim it down to the openssl specific tests that fail).

Have you by chance tested that you can use just one of the dependencies compiled with bitcode inside of a bitcode only app (like, GeoIP is probably the simpler one for doing that)?

I am also interested to know more about your use case: why is bitcode useful for you? To reduce the size of the application? To run on specific devices where bitcode is the only option?

**Comment by ThePatient** [comment]
> Reopened the issue!

Thanks! 

After looking at the config.log it appears the error wasn't actually related to the checking at all. Scrolling up a bit from the openssl complaint I can see clang was complaining about `build/ios/tmp/iphoneos/armv7/lib/lissl.a` missing bitcode. 

In one of my earlier attempts I accidentally overwrote the bitcode included libs with the default ones and when I expanded the tgzs and replaced them I missed a few.

After a successful build, it appears `ndt.o` is still missing bitcode however. Is it insufficient to pass `-fembed-bitcode` to `CFLAGS` and `CXXFLAGS` when running `build/ios/dependency mk`? Should I be doing something more to ensure that all object files end up with bitcode embedded?

>Have you by chance tested that you can use just one of the dependencies compiled with bitcode inside of a bitcode only app (like, GeoIP is probably the simpler one for doing that)?

Nope, haven't tried that yet. I will try that in a few hours when I can get back to this.

>why is bitcode useful for you? 

I am working on a project where I am using obfuscation software that requires bitcode to function.

**Comment by ThePatient** [comment]
Tested the linking on GeoIP with a new project with bitcode enabled successfully.

**Comment by ThePatient** [comment]
Looks like it was a [PEBKAC](https://en.wikipedia.org/wiki/User_error) error after all.

I must have forgotten to run make-frameworks again after compiling mk with bitcode enabled for cc.

I was able to enable bitcode and everything is working now. Thanks!

**Comment by bassosimone** [comment]
Glad to hear that! So, to summarize, one needs to do:

```
export CFLAGS="-fembed-bitcode"
export CXXFLAGS="-fembed-bitcode"
./build/ios/dependency geoip
./build/ios/dependency libressl
./build/ios/dependency libevent
./build/ios/dependency mk
./build/ios/build-frameworks
./build/ios/archive-library
```

to obtain a bitcode enabled build of MK. Correct?

**Comment by bassosimone** [comment]
(@ThePatient the reason why I'm asking is that I'd like to mention the possibility of building bitcode explicitly in the README.md and point out people to this issue: https://github.com/measurement-kit/measurement-kit/pull/1526)

**Comment by ThePatient** [comment]
Yep. That sounds about right presuming `dependency` picks up the `CFLAGS` and `CXXFLAGS` from the environment variable (and doesn't overwrite it).

**Comment by bassosimone** [comment]
> presuming dependency picks up the CFLAGS and CXXFLAGS from the environment variable (and doesn't overwrite it).

Ah, that was not actually the case! I've filed #1528 to address this. Thanks again for testing!

**Comment by bassosimone** [comment]
So, with #1526, I think this can now be closed. We can reopen again in the future in case there are further issues. I can anticipate that I'll rework the build system in #1561 and that, as a result, the commands to build will change. After this specific change, they will become:

```
export CFLAGS="-fembed-bitcode"
export CXXFLAGS="-fembed-bitcode"
# Follow the current instruction for building dependencies for iOS. Flags will be honoured.
```

**Comment by anilsolanki06** [comment]
I want to build MK for tvOS target. Can anyone help me ??
