### ISSUE TITLE
Using also IPPROTO_ICMP for traceroute

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/measurement-kit#683]
Starting point:
- [StackOverflow reply explaining how to implement capability-less ping in JNI](http://stackoverflow.com/a/37456455)
- [ping without capabilities seems to be enabled for all on Android?](https://android.googlesource.com/platform/system/core/+/android-4.4.1_r1/rootdir/init.rc#96)
- https://github.com/bryanyuan/Traceroute

Now the question is whether this would be enough to receive `TIME_EXCEEDED` replies

**Comment by bassosimone** [comment]
Short answer: I don't think so.

**Comment by darkk** [comment]
@bassosimone why? Can you give a long answer, please? I had some plans to eventually implement some traceroutish hacks described at TheTorProject/ooni-probe#647 and I'd love to know show-stoppers for that. I've tested rootless prototypes using Linux desktop, Android may have it's quirks.

**Comment by bassosimone** [comment]
I guess it depend on how you interpret the suggestion of this ticket:

My interpretation was that using `IPPROTO_ICMP` it would have been possible to receive ICMP errors like time exceeded in the way in which it's possible to do with ordinary traceroute.

After thinking a bit more about this, and [after reading the commit message](https://lwn.net/Articles/443051/) and specifically reading this bit:

> ICMP reply packets received from the network are demultiplexed according
to their id's, and are returned by recv() without any modifications.
IP header information and ICMP errors of those packets may be obtained
via ancillary data (IP_RECVTTL, IP_RETOPTS, and IP_RECVERR). ICMP source
quenches and redirects are reported as fake errors via the error queue
(IP_RECVERR); the next hop address for redirects is saved to ee_info (in
network order).

it seems to me using `IPPROTO_ICMP` does not give us anything more than the current scenario where we use `UDP` because we still need to peek into the error queue, like we currently do.

On the contrary, if you interpret this ticket as possibility of using ICMP ping packets to implement passive traceroute, then, I agree with you that having this issue is useful.

Based on my understanding, your interpretation is the latter and you are interested to send ICMP traceroute on Linux and Android *in addition to* the current UDP based traceroute. Let me correct the title of the issue, then, such that the scope is more well defined.

**Comment by darkk** [comment]
Ah, now I see what you mean. I think that both UDP tracroute (btw, you may like [Paris Traceroute](https://paris-traceroute.net/) schema if you have not seen it before) and ICMP traceroute may be meaningful and, of course, some TCP traceroute and TCP+TFO traceroute, and TCP+payload traceroute, and, maybe, something else.

I've written the comment without actually looking at the code, I had an assumption that current traceroute may be as creepy as parsing output of a subprocess :)

**Comment by joelanders** [comment]
@bassosimone @darkk I'm trying to understand what kinds of traceroute are possible on which platforms.

* They all seem to require setting up an ICMP listening socket to receive the TTL exceeded messages, right?
* Some of them send ICMP echo, others send UDP or TCP packets. For all of these, you need to be able to set the TTL. For the Paris/Dublin flow-aware ones, you also need be able to set the source port. Does this mean you need raw sockets?

There seem to be iOS and Android solutions (linked above, for example), but I'm not sure if there are (platform-specific) hacks involved.

I'll keep reading up on it, but if y'all could dump some brain, it'd also be welcome :)

**Comment by bassosimone** [comment]
> They all seem to require setting up an ICMP listening socket to receive the TTL exceeded messages, right?

You can avoid it, if you do not care about knowing what host replied and you care instead of the number of hops that trigger somehow an error. (AFAIK, you need to `connect()` the socket to have some hope that the kernel delivers the ICMP messages as socket errors.)

> Some of them send ICMP echo, others send UDP or TCP packets. For all of these, you need to be able to set the TTL. For the Paris/Dublin flow-aware ones, you also need be able to set the source port. Does this mean you need raw sockets?

No. You can set the source port by calling `bind(socket, sockaddr, socklen)`. I would say that you need raw sockets if you want to craft packets yourself. I do not remember the details but it seems to me you need raw sockets in several environments to prepare an ICMP packet. But this should not be the case on Linux where we have `IPPROTO_ICMP`.

> I'll keep reading up on it, but if y'all could dump some brain, it'd also be welcome :)

With @darkk we discussed something that, if I apply a @bassosimone filter to what we discussed, would probably read something like: refactor the current engine to separate the non portable and the portable part (where the non portable part is accessing the error queue). Then, make the build of the former available on all platforms and write specific platform code that is only enabled when possible for the latter. Make it specifically possible to select whether to enable or not to enable the platform specific code at runtime depending on capabilities (i.e. maybe make the error non fatal and adapt to that). Then iterate over it to add ICMP where possible. Then add TCP. Both TCP and ICMP require some quirks (platform specific for ICMP) and protocol specific for TCP. This is to say that the final traceroute engine will be composed of:

1. portable code for UDP sockets

2. portable code and specific quirks for TCP sockets

3. non portable code to gather detailed errors where possible

4. non portable platform specific code for ICMP

Of all of this, I think I will only take care of the initial step. That is, update the test scaffolding to make it better and refactor the code so that we can have portable UDP sockets code. All the rest is something that I don't think I'm gonna do, but I will be happy to help. I see me doing this refactoring quite soon, as it's part of related UDP improvements that I'm working on also for DNS.

**Comment by bassosimone** [comment]
https://github.com/ooni/probe-engine/issues/46
