### ISSUE TITLE
Implement HTTP Header Field manipulation test

### ISSUE THREAD

**Issue by hellais** [measurement-kit/measurement-kit#692]
In order to reach feature parity with ooni-probe and begin the process of transitioning over to using measurement-kit as the testing engine of ooni-probe (see: https://github.com/TheTorProject/ooni-probe/issues/558) we should add support for the HTTP Header Field manipulation test.

The specification: https://github.com/TheTorProject/ooni-spec/blob/master/test-specs/ts-006-header-field-manipulation.md
The implementation in ooni-probe: https://github.com/TheTorProject/ooni-probe/blob/master/ooni/nettests/manipulation/http_header_field_manipulation.py

**Comment by bassosimone** [comment]
This has now been merged in master.
