### ISSUE TITLE
Add support for cloudfronting in measurement-kit

### ISSUE THREAD

**Issue by hellais** [measurement-kit/measurement-kit#694]
In order to circumvent censorship measurement-kit should support, like ooni-probe, the ability to communicate to backends (collectors, bouncers and test-helpers) via cloudfronting.

**Comment by bassosimone** [comment]
Initial support implemented in #907 will followup in #911. More TODO before closing.

**Comment by bassosimone** [comment]
I guess this issue can be closed in favor of #911: it does not make sense to keep multiple issues open all pointing to the same real issue from different angles. Let's reduce entropy a little bit.
