### ISSUE TITLE
ooni: count the entries before running a test

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/measurement-kit#707]
It would be helpful to count the entries in a input file before running a test. That would allow us to pass precise progress information to the Apps.

**Comment by hellais** [comment]
Yes I think this is a worthwhile thing to have and I don't think it adds too much overhead. While we are scanning the input file we may as well use this as a chance to also randomise the order in which we go through the inputs as was requested as a feature for ooniprobe in https://github.com/TheTorProject/ooni-probe/issues/480
