### ISSUE TITLE
geoip: memoize previously opened dbs to allow reuse

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/measurement-kit#736]

**Comment by AntonioLangiu** [comment]
If the meaning of this issue was to be able to handle multiple queries with an open database I think it is done in #759 (if not, @bassosimone can you give me more details about it)

**Comment by bassosimone** [comment]
Uhm, yes and no. The main problem, I guess, is that I incorrectly worded the issue. I agree with you that the class already allows to reuse existing connections. However, in practice, the current code instances the class and destroys it every time. This is not totally incorrect, because each test could in principle receive different paths for the databases. What I'd like to see is that, if we already did open a database for a specific set of paths, we re-use it. Otherwise, we close the previously opened database and open a new one. A sort of one-off memoization.

Is the issue clearer now?

**Comment by bassosimone** [comment]
This has now been merged into master.
