### ISSUE TITLE
settings: reimplement using nlohmann::json

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/measurement-kit#837]
I believe that `Settings` should probably be a subclass of `nlohmann::json`, now that we have decided to distribute the latter along with MK. This should allow us to remove some code (thinking of `SettingsEntry` and perhaps also of `lexical_cast<>`<sup>1</sup>) and additionally it would allow us to specify settings using a non flat structure such as the following:

``` JSON
{
    "web_connectivity": {
        "backend": "https://a.collector.test.ooni.io:4444",
        "name_server": "8.8.8.8:53"
    },
    "ooni": {
        "collector_base_url": "https://measurement-kit-collector.herokuapp.com",
        "max_retries": 3
    }
```

Keeping settings into a class that can be converted from/to JSON has two other advantages in addition to allowing for non flat data structures:
1. we can receive settings over a web API (assuming we want MK to have one)
2. it simplifies talking with scripting languages because settings could be passed in as JSON (note that in #824 we are already passing out entries as JSON)
# Notes

<sup>1</sup> I am not sure we can _completely_ remove `lexical_cast` but I believe it should be possible to implement it in terms of `nlohmann::json`.

**Comment by AntonioLangiu** [comment]
I was trying to implement this solution and I noticed that

- `nlohmann:json` supports convertion just for compatible types, you can convert an int to a long or a double, but not a std::string to a double. This was supported by out SettingEntry implementation! We could implement it using lexical cast but the code will be not so clean.
- if we want to set the options via a json, the `set_option` API should take a `nlohmann:json` object and not a std::string. Does this makes things harder when using the API with Android (and JNI)??

**Comment by bassosimone** [comment]
I think that, for now `Settings` can stay as-is. Honestly, recently I was thinking the converse, i.e. that `Settings` should be an explicit structure with fields inside it. That would make knowing easily what options are available and what are not available more easy.
