### ISSUE TITLE
transport.hpp: hide Transport class by default

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/measurement-kit#849]
This is simple. Just wrap the class with `#ifdef MK_TRANSPORT_VISIBLE ... #endif` and the recompile and notice all the places using the class explicitly. I bet that most places, except places where the class itself is defined, should better use the wrapper functions `read`, `readn`, etc.

**Comment by AntonioLangiu** [comment]
I checked all the files containing a `Transport variable` searching recursively with grep, but I was not able to find cases when the class is used for unidirectional communication. Do you have some advice for this issue? Can you show me some place where I should change the Transport method in favor of the wrapper functions?

**Comment by bassosimone** [comment]
I suggest you surround the class definition with

```C++

#ifdef MK_TRANSPORT_VISIBLE
// ...
#endif
```

Then recompile with `make -k` and note all the places where this fails and add the define on top of failing C++ files to repair the build. This would allow us to see all the places where we're using the Transport directly and then we can judge whether there are places where we can use more abstract APIs.

(It's possible that we're already using the optimal thing and this pull request would lead to pretty much noting if that is the case.)

**Comment by bassosimone** [comment]
After some discussions, we've seen that the definition of transport is useful in many placed and we would gain little by making it more private than this. Closing this issue.
