### ISSUE TITLE
Integrate Tor

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/measurement-kit#86]
[Probably not our top priority at the moment, however, adding this issue so I am sure that I do not lose my notes and to state in advance what I think we should do.]

We need to integrate Tor with libight to submit ooni reports (and to enable the possibility of using Tor during ooni and other tests). We can use as blueprint projects such as [Orbot](https://gitweb.torproject.org/orbot.git/), [OnionBrowser](https://github.com/OnionBrowser/iOS-OnionBrowser) and [CPAProxy](https://github.com/ursachec/CPAProxy).

The first step to do this is to compile Tor. All the projects mentioned above provide scripts that set the proper environment variables and then use the GNU build system (`autoreconf`, `./configure` and `make`). We should do the same (also because we already integrate `libevent` which is also a dependency of Tor). The way to go is the following: put Tor and its dependencies in `src/ext` and massage the build system so that we end up with all the libraries (`libight.a`, `libevent.a`, `libor.a` and so on) and the headers we need into a specific directory. The integrator, then, only needs to copy this directory to the proper place to pull libight, its headers and its dependencies.

The second step concerns how to run Tor. On iOS systems OnionBrowser and CPAProxy execute the Tor process in a separate thread. On Android, Orbot includes the Tor executable as a resource and executes it using the shell (see also #85). To start off, we should probably follow the same approach on all platforms, for simplicity, that is we should run Tor in a separate thread. In C++11 this task should be easy enough using `std::async`.

A related task is to decide how to configure the instance of Tor that we run. IIRC all the projects mentioned above (and for sure CPAProxy) instruct Tor to open a control connection and use such control connection. It is not completely clear yet to me the purpose of this, and we should investigate whether we need to do that in our use case (for example, do we need a control connection to cleanly tear down the Tor thread?).

**Comment by bassosimone** [comment]
We use `https` on mobile. We may possibly be using also `cloudfronting` in the future. For now, we're fine following this strategy. My research on the topic is now starting to be a bit outdated. Anyway, unless a Tor core developer helps to make Tor more easily usable as a library, I believe it would be in any case very complex to integrate it. Perhaps, it is something we should do in the apps.

**Comment by hellais** [comment]
I am reopening this issue as maybe we can get some Tor people interested in doing this.

**Comment by bassosimone** [comment]
Since there has been recent interest on that (this is great!) perhaps I can expand a little more on what we tried, what went well, and what was wrong. As said by @hellais on IRC, we were aiming to always execute Tor in the same way on all platforms for uniformity. As @darkk pointed out, this is an assumption that we may want to relax (however, if possible, I'd really rather pursue the goal of uniformity).

When we were trying to develop this feature, one attempt we made was to integrate directly the event loop of Tor and the event loop of measurement-kit. Specifically, the idea was to write a specialization of our `Reactor` (i.e. the event loop manager) that used the Tor event loop as loop, as opposed to the event loop of libevent. Since internally Tor uses libevent, the Tor event loop was basically libevent's event loop plus external code. See bassosimone/mkok-onion-event#2.

Honestly, the above approach may not have been the best approach ever [*]. If one wants to do Tor as a library, it's not granted that he/she is using libevent. Yet, I cite this in this thread because I was able to understand what are the main things that need to be done to simplify bundling Tor:

1. the build process should be instrumented to produce a shared library

2. there should be an header exposing an API allowing to control the Tor event loop (startup / shutdown)

3. the event loop should be reentrant

In bassosimone/mkok-onion-event#2 I did the first two points, but I didn't do the third one. The problem with the third one is that, AFAICT, there are many global objects on Tor that are not happy if they are initialized more than once. [Thus, if one exits the Tor event loop and then reenters it, the program crashes](https://github.com/bassosimone/mkok-onion-event/pull/2/files#diff-cbe1c76f922ae00892d6e583ae9ada6dR3548).

For mobile apps, we really need to be able to start up Tor, use it, and then tear it down. I think it's not acceptable to have a thread always running Tor. We want the app to pause fully, when idle.

(I reckon that we can probably have this property on Android by running and then killing the Tor process but I really see this as ghetto and believe it would be better to have a "Tor thread" we can control.)

I also think that there should be some more advanced bundling of pluggable transports such that we can deploy and use them more easily on mobile. My vague understanding is that pluggable transports need to be executed as external processes and I am not completely sure we can do that on iOS. But perhaps is better that on this specific aspect @hellais steps in and adds further comments.

To wrap up, we need:

1. a shared library with an header

2. the possibility to startup and teardown the tor event loop multiple times [**]

3. a more easy way of handling pluggable transports (?)

[*] I described this sort of loop sharing to nickm in Valencia (I think 2016) and he replied: "it's a custom setup, I cannot guarantee things will not break."

[*(] No need to have threading inside Tor. We are happier using C++14 thread features and to fully control ourselves the life cycle of such thread.

**Comment by hellais** [comment]
> a more easy way of handling pluggable transports (?)

I can add a couple more sentences on this, but it was quite some time ago so my memory may be betraying me.

On this topic, if my memory does not betray me, I think the issue is that Tor expects to be able to start a process (and maybe fork?) and it communicates with the pluggable transports via environment variables. This is something that is tricky to do on all platforms (especially iOS) and as such it would be better if there were some API level way to "link" a pluggable transport with the tor daemon.

I bet this is actually super hard to do as it's part of the core design of PTs and tor.

**Comment by teor2345** [comment]
Tor now has a supported embedding API:
https://gitweb.torproject.org/tor.git/tree/src/or/tor_api.h

Please try it out, and let us know how it works for you.

**Comment by bassosimone** [comment]
moved here https://github.com/ooni/probe-engine/issues/81
