### ISSUE TITLE
Update Android make-toolchaing script

### ISSUE THREAD

**Issue by AntonioLangiu** [measurement-kit/measurement-kit#884]
With the latest changes of Android NDK we are no more able to build the dependencies.
This can be solved looking how the new script for building the toolchain works and updating the make-toolchain script.

**Comment by bassosimone** [comment]
I don't know: I've installed Android NDK 13.1.3345770 on my system using Android studio and the required script is still there. Perhaps this is just an issue of the NDK installed using `brew`.
