### ISSUE TITLE
dns: support multi dns settings

### ISSUE THREAD

**Issue by AntonioLangiu** [measurement-kit/measurement-kit#904]
With the actual api we are able to set just one DNS resolver, due to the fact that the settings doesn't support multiple values. I discovered this trying measurement-kit on Android on a network where the first DNS resolver (that was the only one setted on measuremen-kit) was not working. 

This depends on #837

**Comment by AntonioLangiu** [comment]
A possible solution for this problem if we are not able to use json as settings is to have more fields for dns nameserver, like 

    dns/nameserver1
    dns/nameserver2
    dns/nameserver3
    dns/nameserverN

**Comment by bassosimone** [comment]
I think it's important to enable this in v0.9.0 where, in particular, we'll also have `c-ares`.

**Comment by bassosimone** [comment]
Will consider doing something like that in https://github.com/ooni/probe-engine/issues/18
