### ISSUE TITLE
Add support for zlib

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/measurement-kit#984]
Support for zlib is required to uncompress GeoIP databases.

**Comment by bassosimone** [comment]
I've done some research and this seems to me simple enough to try to implement it within the next release window. See for example [how OpenSMTPD deals with the matter](https://github.com/OpenSMTPD/OpenSMTPD/blob/portable/smtpd/compress_gzip.c).

**Comment by hellais** [comment]
I think this would be a fairly important feature to have, mainly to support gzip compression in HTTP requests.

BTW what do we do now when a server response is served with gzip compression?

**Comment by bassosimone** [comment]
> BTW what do we do now when a server response is served with gzip compression?

Nothing; i.e., the response is not uncompressed but saved into the JSON as a base64.

**Comment by bassosimone** [comment]
We have zlib support in the ooni/probe-engine engine, since it's written in Go. No further action is required here in MK even though we may create an issue for #1315 in ooni/probe-engine.
