### ISSUE TITLE
Automatically run regress tests through Valgrind

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/measurement-kit#99]
It should be useful to run regress tests through Valgrind. To this end, we should create a script that compiles libight using `./configure --disable-shared` and than run each regress test script using `valgrind --error-exitcode=1` so that, if there is a memory error or a leak, `make check` fails.

**Comment by bassosimone** [comment]
First thing I'd check is whether it's possible to run valgrind as a service with github integration like now we run travis-ci. Another possibility is to enhance travis-ci script to also run regress tests through a script that proxies regress tests through valgrind. I think we can directly use [the script that v8 folks use to run their tests through valgrind for this purpose](https://github.com/v8/v8/blob/master/tools/run-valgrind.py).

**Comment by AntonioLangiu** [comment]
I'm working on this and it should be quite done. You can see the progess in [this PR](https://github.com/measurement-kit/measurement-kit/pull/319)

**Comment by bassosimone** [comment]
I believe this should not be patched into the existing test mechanism, rather this should be *another* test that we run on travis (i.e. probably the sanest way to implement this is a build matrix).

**Comment by AntonioLangiu** [comment]
To enable Valgrind inside Travis we should first fix this two memory leaks:

* [test/common/delayed_call](https://github.com/measurement-kit/measurement-kit/issues/320)
* [test/net/connection](https://github.com/measurement-kit/measurement-kit/issues/191)

**Comment by bassosimone** [comment]
Alright, I've modified the issue name accordingly!

**Comment by bassosimone** [comment]
This feature has been implemented in #328. Currently valgring is failing but we know how to deal with it and the failing run is allowed to fail in travis configuration. Closing this issue.
